Repository public-ui/kolibri, pull requests merged in 2023-12, with the labels that each got.

#5703 a11y: always preset font and background color
  packages/components/src/components/a11y.css
  packages/themes/ecl/snapshots/theme-ecl_ec/snapshot-for-input-file-basic-firefox-darwin.png
  packages/themes/ecl/snapshots/theme-ecl_eu/snapshot-for-input-file-basic-firefox-darwin.png
  packages/themes/zoll/snapshots/theme-zollv3/snapshot-for-table-badge-size-firefox-darwin.png
Labels: optional

#5702 a11y: always preset font and background color
  packages/components/src/components/a11y.css
  packages/themes/mfm/snapshots/theme-mfm/snapshot-for-input-file-basic-firefox-darwin.png
Labels: optional

#5734 Set host background colors back to transparent for all themes
  packages/themes/bmf/src/index.ts
  packages/themes/bzst/src/global.scss
  packages/themes/default/src/index.ts
  packages/themes/ecl/src/ecl-ec.ts
  packages/themes/ecl/src/ecl-eu.ts
  packages/themes/itzbund/src/index.ts
  packages/themes/mfm/src/index.ts
  packages/themes/src/themes/desy-v1.ts
  packages/themes/src/themes/desy-v2.ts
  packages/themes/zoll/src/mapz.ts
  packages/themes/zoll/src/v3/index.ts
  packages/themes/zoll/src/zoll-v2.ts
Labels: in V2

#5802 fix: lazy initialization of the global KoliBri context
  packages/components/src/components/modal/component.tsx
  packages/components/src/core/index.ts
  packages/components/src/global/devtools.ts
  packages/components/src/utils/dev.utils.ts
Labels: in V2

#5797 Add draft-deploy workflow
  .github/workflows/draft-deploy.yml
Labels: Do not merge!

#5815 Fix screen reader content for external links
  packages/components/src/components.d.ts
  packages/components/src/components/link-button/component.tsx
  packages/components/src/components/link/component.tsx
  packages/components/src/components/link/readme.md
  packages/components/src/components/link/shadow.tsx
  packages/components/src/components/link/test/html.mock.ts
  packages/components/src/components/link/test/snapshot.spec.tsx
  packages/components/src/components/link/types.ts
  packages/components/src/locales/de.ts
  packages/components/src/locales/en.ts
  packages/components/src/types/button-link-text.ts
Labels: needs a11y-tests

#5780 Improve accessibility for sortable table columns
  KNOWN_ISSUES.md
  packages/components/src/components/table/component.tsx
  packages/components/src/components/table/readme.md
  packages/components/src/components/table/style.css
  packages/components/src/dev/theme-registration.ts
  packages/components/src/locales/de.ts
  packages/components/src/locales/en.ts
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/src/components/table/column-alignment.tsx
  packages/samples/react/src/components/table/routes.ts
  packages/samples/react/src/components/table/sort-data.tsx
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-complex-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-table-column-alignment-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-table-sort-data-firefox-linux.png
  packages/themes/bmf/src/index.ts
  packages/themes/bzst/snapshots/theme-bzstv1/snapshot-for-table-column-alignment-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-table-column-alignment-firefox-linux.png
  packages/themes/default/src/index.ts
  packages/themes/ecl/src/ecl-ec.ts
  packages/themes/ecl/src/ecl-eu.ts
  packages/themes/itzbund/src/index.ts
  packages/themes/zoll/snapshots/theme-mapz/snapshot-for-table-column-alignment-firefox-linux.png
  packages/themes/zoll/snapshots/theme-zollv2/snapshot-for-table-column-alignment-firefox-linux.png
  packages/themes/zoll/snapshots/theme-zollv3/snapshot-for-table-column-alignment-firefox-linux.png
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: Do not merge!, needs a11y-tests
