Repository public-ui/kolibri, pull requests merged in 2023-08, with the labels that each got.

#4393 chore: initial sample
  packages/components/package.json
  packages/components/pnpm-lock.yaml
  packages/components/src/components/icon/test/html.mock.ts
  packages/components/src/components/icon/test/icon.pug
Labels: Feature

#4661 chore: remove hide-label prop from badge
  packages/components/src/components.d.ts
  packages/components/src/components/badge/component.tsx
  packages/components/src/components/badge/test/html.mock.ts
  packages/components/src/components/badge/test/snapshot.spec.tsx
  packages/components/src/components/badge/types.ts
Labels: Feature

#4662 fix: correct link to architecture docu
  CONTRIBUTING.md
Labels: Documentation

#4676 refact: refactor initial solution
  packages/components/src/components/input-range/component.tsx
  packages/components/src/components/input-range/style.css
  packages/components/src/index.html
Labels: Feature

#4533 Workspace setup
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  lerna.json
  nx.json
  package.json
  packages/adapters/svelte/.gitignore
  packages/adapters/svelte/LICENSE
  packages/adapters/svelte/README.md
  packages/adapters/svelte/package.json
  packages/adapters/svelte/pnpm-lock.yaml
  packages/adapters/svelte/tsconfig.json
  packages/components/package.json
  packages/components/stencil.config.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/tsconfig.json
  packages/create-kolibri/README.md
  packages/create-kolibri/templates/angular-app/tsconfig.app.json
  packages/create-kolibri/templates/kolibri-library/packages/components/package.json
  packages/designer/.eslintrc.js
  packages/designer/README.md
  packages/designer/package.json
  packages/designer/src/components/app/component.solid.tsx
  packages/designer/src/components/editor/store.tsx
  packages/designer/tsconfig.json
  packages/samples/react/package.json
  packages/samples/react/src/App.tsx
  packages/samples/react/src/react.main.tsx
  packages/samples/react/src/samples/select/basic.tsx
  packages/samples/react/src/samples/table/badge-size.tsx
  packages/samples/react/src/samples/table/render-cell.tsx
  packages/storybook/src/3-integrationen.stories.mdx
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/license-reports.sh
Labels: Feature

#5020 Fix/input radio slot handling
  packages/components/src/components/input/component.tsx
  packages/components/src/dev.html
  packages/samples/react/src/samples/input-radio/horizontal.tsx
  packages/samples/react/src/samples/input-radio/routes.ts
Labels: Bug
