Repository public-ui/kolibri, pull requests merged in 2023-09, with the labels that each got.

#5099 feat: markdown support for badgets
  packages/components/package.json
  packages/components/src/components.d.ts
  packages/components/src/components/badge/component.tsx
  packages/components/src/components/badge/test/html.mock.ts
  packages/components/src/components/badge/test/snapshot.spec.tsx
  packages/components/src/components/link/test/html.mock.ts
  packages/components/src/components/span/component.tsx
  packages/components/src/components/span/style.css
  packages/components/src/components/span/test/html.mock.ts
  packages/components/src/components/span/types.ts
  packages/components/src/components/tooltip/test/html.mock.ts
  packages/components/src/components/version/test/html.mock.ts
  packages/components/src/components/version/test/snapshot.spec.tsx
  packages/components/src/utils/markdown.ts
  pnpm-lock.yaml
Labels: Feature

#5123 fix: error handling
  packages/tools/kolibri-cli/package.json
  packages/tools/kolibri-cli/src/index.ts
  packages/tools/kolibri-cli/src/migrate/index.ts
  packages/tools/kolibri-cli/src/migrate/runner/abstract-task.ts
  packages/tools/kolibri-cli/src/migrate/runner/task-runner.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/common/GenericRenamePropertyTask.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/common/LabelExpertSlot.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/common/RemovePropertyNameTask.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/test/index.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/v1/index.ts
  packages/tools/kolibri-cli/src/migrate/shares/reuse.ts
Labels: Feature

#5294 Revert "Revert "5100 checkbox icons für checked indeterminate unchecked""
  packages/components/src/components/input-checkbox/common.css
  packages/components/src/components/input-checkbox/component.tsx
  packages/components/src/components/input-checkbox/switch.css
  packages/components/src/dev.html
  packages/components/src/dev/theme-registration.ts
  packages/themes/bmf/src/index.ts
  packages/themes/default/src/index.ts
  packages/themes/itzbund/src/index.ts
  packages/themes/src/themes/desy-v2.ts
  packages/themes/zoll/src/mapz.ts
  packages/themes/zoll/src/zoll-v2.ts
Labels: Bug, Do not merge!

#5299 Visual Test needs a better path resolver
  packages/tools/visual-tests/src/index.js
Labels: Bug

#5300 chore: optimize switch icon positioning
  packages/components/src/components.d.ts
  packages/components/src/components/input-checkbox/component.tsx
  packages/components/src/components/input-checkbox/controller.ts
  packages/components/src/components/input-checkbox/switch.css
  packages/components/src/components/input-checkbox/types.ts
  packages/samples/react/src/components/input-checkbox/partials/variants.tsx
Labels: Bug, Feature

#5323 fix: link component attribute download with string content for file names
  packages/components/src/components/link/component.tsx
  packages/components/src/components/link/test/html.mock.ts
  packages/components/src/components/link/test/snapshot.spec.tsx
Labels: Feature, vor V2
