Repository public-ui/kolibri, pull requests merged in 2023-06, with the labels that each got.

#3364 chore: auto dependency update
  package.json
  packages/adapters/angular/v11/package.json
  packages/adapters/angular/v11/pnpm-lock.yaml
  packages/adapters/angular/v12/package.json
  packages/adapters/angular/v12/pnpm-lock.yaml
  packages/adapters/angular/v13/package.json
  packages/adapters/angular/v13/pnpm-lock.yaml
  packages/adapters/angular/v14/package.json
  packages/adapters/angular/v14/pnpm-lock.yaml
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v15/pnpm-lock.yaml
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v16/pnpm-lock.yaml
  packages/adapters/hydrate/pnpm-lock.yaml
  packages/adapters/preact/pnpm-lock.yaml
  packages/adapters/react/package.json
  packages/adapters/react/pnpm-lock.yaml
  packages/adapters/solid/package.json
  packages/adapters/solid/pnpm-lock.yaml
  packages/adapters/vue/package.json
  packages/adapters/vue/pnpm-lock.yaml
  packages/components/package.json
  packages/components/pnpm-lock.yaml
  packages/core/package.json
  packages/core/pnpm-lock.yaml
  packages/create-kolibri/package.json
  packages/create-kolibri/pnpm-lock.yaml
  packages/designer/package.json
  packages/designer/pnpm-lock.yaml
  packages/samples/react/package.json
  packages/samples/react/pnpm-lock.yaml
  packages/schema/package.json
  packages/schema/pnpm-lock.yaml
  packages/slidev/pnpm-lock.yaml
  packages/storybook/package.json
  packages/storybook/pnpm-lock.yaml
  packages/themes/bmf/package.json
  packages/themes/bmf/pnpm-lock.yaml
  packages/themes/bpa/package.json
  packages/themes/bpa/pnpm-lock.yaml
  packages/themes/ecl/ec/package.json
  packages/themes/ecl/ec/pnpm-lock.yaml
  packages/themes/ecl/eu/package.json
  packages/themes/ecl/eu/pnpm-lock.yaml
  packages/themes/itzbund/package.json
  packages/themes/itzbund/pnpm-lock.yaml
  packages/themes/package.json
  packages/themes/pnpm-lock.yaml
  pnpm-lock.yaml
Labels: do not merge

#3526 remove redundant documentation
  README.md
  docs/ARCHITECTURE.md
  docs/GET_STARTED.md
Labels: documentation

#3614 chore: optimize progress bordering
  packages/components/src/components.d.ts
  packages/components/src/components/progress/component.tsx
  packages/components/src/components/progress/style.css
  packages/components/src/components/progress/test/snapshot.spec.tsx
  packages/components/src/index.bak.html
  packages/components/src/index.html
Labels: enhancement

#3613 3514 bug radio inputs müssen unterschiedliche slot namen bekommen
  packages/components/src/components.d.ts
  packages/components/src/components/input-radio/component.tsx
  packages/components/src/components/input/component.tsx
  packages/components/src/components/input/types.ts
Labels: do not merge

#3666 Refactor: remove unnecessary prop reflections
  packages/components/src/components/alert/component.tsx
  packages/components/src/components/alert/shadow.tsx
  packages/components/src/components/alert/test/html.mock.ts
  packages/components/src/components/badge/component.tsx
  packages/components/src/components/badge/test/html.mock.ts
  packages/components/src/components/button-link/component.tsx
  packages/components/src/components/button/component.tsx
  packages/components/src/components/button/shadow.tsx
  packages/components/src/components/card/component.tsx
  packages/components/src/components/card/test/html.mock.ts
  packages/components/src/components/input-checkbox/component.tsx
  packages/components/src/components/input-color/component.tsx
  packages/components/src/components/input-date/component.tsx
  packages/components/src/components/input-email/component.tsx
  packages/components/src/components/input-file/component.tsx
  packages/components/src/components/input-number/component.tsx
  packages/components/src/components/input-password/component.tsx
  packages/components/src/components/input-radio-group/component.tsx
  packages/components/src/components/input-radio/component.tsx
  packages/components/src/components/input-range/component.tsx
  packages/components/src/components/input-text/component.tsx
  packages/components/src/components/input/component.tsx
  packages/components/src/components/kolibri/component.tsx
  packages/components/src/components/link-button/component.tsx
  packages/components/src/components/link-group/component.tsx
  packages/components/src/components/link/component.tsx
  packages/components/src/components/link/shadow.tsx
  packages/components/src/components/link/test/html.mock.ts
  packages/components/src/components/select/component.tsx
  packages/components/src/components/span/component.tsx
  packages/components/src/components/span/shadow.tsx
  packages/components/src/components/span/test/html.mock.ts
  packages/components/src/components/spin/component.tsx
  packages/components/src/components/spin/test/html.mock.ts
  packages/components/src/components/split-button/component.tsx
  packages/components/src/components/textarea/component.tsx
  packages/components/src/components/toast/component.tsx
  packages/components/src/components/toast/test/html.mock.ts
  packages/components/src/components/toast/test/snapshot.spec.tsx
Labels: do not merge

#3667 Fix/stencil hidden hydrate anomaly
  packages/components/src/components/button/component.tsx
  packages/components/src/components/button/test/html.mock.ts
  packages/components/src/components/link/component.tsx
  packages/components/src/components/link/test/html.mock.ts
Labels: do not merge

#3668 refact: button link text switch component
  packages/components/src/components.d.ts
  packages/components/src/components/button-link-text-switch/component.tsx
  packages/components/src/components/button-link-text-switch/types.ts
  packages/components/src/components/nav/component.tsx
  packages/components/src/types/button-link-text.ts
Labels: do not merge
