Repository public-ui/kolibri, pull requests merged in 2024-04, with the labels that each got.

#6279 Fix: Call input components onChange before form onSubmit
  packages/components/src/components/form/component.tsx
  packages/components/src/components/form/controller.ts
Labels: v2

#6292 Pagination: Fix slot rendering when elements change
  packages/components/src/components/pagination/component.tsx
  packages/samples/react/src/components/table/with-pagination.tsx
Labels: v1

#6296 Improve Tooltip and Popover Readmes
  packages/components/src/components/popover/readme.md
  packages/components/src/components/tooltip/readme.md
Labels: v1

#6297 Improve Tooltip and Popover Readmes
  packages/components/src/components/popover/readme.md
  packages/components/src/components/tooltip/readme.md
Labels: v2

#6305 (#6201) Add prepare-commit-msg git hook which validates branch names and automatically prepends ticket IDs
  .gitignore
  .husky/prepare-commit-msg
  package.json
Labels: v1

#6192 fix: add schema types to components
  packages/components/src/index.ts
Labels: do not merge, v2

#6319 Add prepare-commit-msg git hook which validates branch names and automatically prepends ticket IDs
  .gitignore
  .husky/prepare-commit-msg
  package.json
Labels: v2

#6318 Tabs: Remove delay when changing tabs, fixing faulty focus state
  packages/components/src/components/tabs/component.tsx
Labels: v1

#6337 Make Git hook POSIX compatible for support on all environments
  .husky/prepare-commit-msg
Labels: v2

#6357 Add value to input events
  packages/components/src/components/@deprecated/input/controller.ts
  packages/components/src/components/input-checkbox/component.tsx
  packages/components/src/components/input-radio/component.tsx
  packages/components/src/components/select/component.tsx
  packages/components/src/types/input/types.ts
Labels: v1
