Repository public-ui/kolibri, pull requests merged in 2024-06, with the labels that each got.

#6505 Changed tooltip delay
  packages/components/src/components/tooltip/component.tsx
Labels: v1

#6502 Changed tooltip delay
  packages/components/src/components/tooltip/component.tsx
Labels: v2

#6477 Implement selection feature for KolTableStateful
  packages/components/src/components/table-stateful/readme.md
  packages/components/src/components/table-stateful/shadow.tsx
  packages/components/src/components/table-stateless/component.tsx
  packages/components/src/components/table/readme.md
  packages/components/src/components/table/shadow.tsx
  packages/components/src/schema/components/table.ts
  packages/components/src/schema/props/table-callbacks.ts
  packages/samples/react/src/components/table/routes.ts
  packages/samples/react/src/components/table/stateful-with-selection.tsx
Labels: v2

#6498 Fix high contrast mode for radio buttons
  packages/components/src/components/input-radio/style.scss
Labels: a11y-retest

#6499 Issue discussion templates & workflow update
  .github/DISSCUSSION_TEMPLATE/ideas.yml
  .github/DISSCUSSION_TEMPLATE/q-a.yml
  .github/ISSUE_TEMPLATE/1.bug_report.yml
  .github/ISSUE_TEMPLATE/2.doc_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/issue-validation.yml
  packages/tools/kolibri-cli/README.md
  packages/tools/kolibri-cli/src/index.ts
  packages/tools/kolibri-cli/src/info/index.ts
Labels: feature, intern

#6507 Fix onChange issue in input text
  packages/components/src/components/input-text/component.tsx
Labels: v1

#6503 Fix onChange issue in input text
  packages/components/src/components/input-text/shadow.tsx
Labels: v2

#6491 Improve Combobox accessibility and focus management
  packages/components/src/components/combobox/shadow.tsx
Labels: a11y-retest

#6523 Display build date and commit hash in sidebar
  packages/samples/react/src/App.tsx
  packages/samples/react/src/components/Sidebar.tsx
  packages/samples/react/webpack.config.js
Labels: v2

#6479 Display build date and commit hash in sidebar
  packages/samples/react/src/App.tsx
  packages/samples/react/src/components/Sidebar.tsx
  packages/samples/react/webpack.config.js
  pnpm-lock.yaml
Labels: v1

#6535 Standardisation of Textarea
  packages/components/src/components/textarea/controller.ts
  packages/components/src/components/textarea/readme.md
  packages/components/src/components/textarea/shadow.tsx
  packages/components/src/schema/components/textarea.ts
Labels: feature, v2

#6538 Add ESLint rule no-console
  packages/components/.eslintrc.js
  packages/components/src/components/form/controller.ts
  packages/components/src/components/icon-font-awesome/readme.md
  packages/components/src/components/icon-icofont/readme.md
  packages/components/src/components/tabs/readme.md
  packages/components/src/components/toast/toaster.tsx
  packages/components/src/components/toaster/toaster.tsx
  packages/components/src/dev/input-error.ts
  packages/components/src/types/props/color.ts
  packages/components/src/utils/dev.utils.ts
  packages/components/src/utils/unique-nav-labels.ts
Labels: v1

#6540 Enable ESLint rule 'no-console' and refactor console usages to utilize Log service
  packages/components/.eslintrc.js
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/form/controller.ts
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/toaster/toaster.tsx
  packages/components/src/dev/input-error.ts
  packages/components/src/schema/props/color.ts
  packages/components/src/schema/utils/dev.utils.ts
  packages/components/src/utils/unique-nav-labels.ts
Labels: v2

#6550 Bugfix CLI command in issue template
  .github/ISSUE_TEMPLATE/1.bug_report.yml
Labels: bug

#6557 Remove Angular adapters for unsupported versions
  .github/workflows/publish.yml
  lerna.json
  packages/adapters/angular/v11/.gitignore
  packages/adapters/angular/v11/LICENSE
  packages/adapters/angular/v11/README.md
  packages/adapters/angular/v11/ng-module.js
  packages/adapters/angular/v11/package.json
  packages/adapters/angular/v11/tsconfig.json
  packages/adapters/angular/v12/.gitignore
  packages/adapters/angular/v12/LICENSE
  packages/adapters/angular/v12/README.md
  packages/adapters/angular/v12/ng-module.js
  packages/adapters/angular/v12/package.json
  packages/adapters/angular/v12/tsconfig.json
  packages/adapters/angular/v13/.gitignore
  packages/adapters/angular/v13/LICENSE
  packages/adapters/angular/v13/README.md
  packages/adapters/angular/v13/ng-module.js
  packages/adapters/angular/v13/package.json
  packages/adapters/angular/v13/tsconfig.json
  packages/adapters/angular/v14/.gitignore
  packages/adapters/angular/v14/LICENSE
  packages/adapters/angular/v14/README.md
  packages/adapters/angular/v14/ng-module.js
  packages/adapters/angular/v14/package.json
  packages/adapters/angular/v14/tsconfig.json
  packages/components/package.json
  packages/components/src/components/icon-font-awesome/readme.md
  packages/components/src/components/icon-icofont/readme.md
  packages/components/src/components/tabs/readme.md
  packages/components/stencil.config.ts
  packages/create-kolibri/README.md
  pnpm-lock.yaml
  scripts/dist-tags.sh
  scripts/license-reports.sh
Labels: v1

#6572 Remove old dev code
  packages/components/package.json
  packages/components/src/dev.html
  packages/components/src/dev/details-synced-open-state.html
  packages/components/src/dev/details-synced-open-state.ts
  packages/components/src/dev/index.ts
  packages/components/src/dev/input-error.html
  packages/components/src/dev/input-error.ts
  packages/components/src/dev/inputs-hide-error.html
  packages/components/src/dev/reprod-accordion-does-not-toggle-with-open.html
  packages/components/src/dev/reprod-accordion-does-not-toggle-with-open.ts
  packages/components/src/dev/required-inputs-hide-labels.html
  packages/components/src/dev/theme-registration.ts
  packages/components/src/dev/toaster.html
  packages/components/src/dev/toaster.ts
  packages/components/src/global/script.ts
  packages/components/src/index.html
Labels: v1
