Repository public-ui/kolibri, pull requests merged in 2024-07, with the labels that each got.

#6591 Combobox: Fehlerhafte Events
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/input-adapter-leanup/associated.controller.ts
  packages/samples/react/src/components/combobox/partials/cases.tsx
  packages/samples/react/src/scenarios/inputs-get-value.tsx
  packages/samples/react/src/scenarios/static-form.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-static-form-firefox-linux.png
Labels: bug, v2

#6588 Publish workflow: Bump versions automatically
  .github/workflows/publish.yml
  package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/hydrate/package.json
  packages/adapters/preact/package.json
  packages/adapters/react-standalone/kolibri-rock's.html
  packages/adapters/react-standalone/package.json
  packages/adapters/solid/package.json
  packages/adapters/vue/package.json
  packages/components/package.json
  packages/components/src/utils/dev.utils.ts
  packages/components/stencil.config.ts
  packages/core/package.json
  packages/create-kolibri/package.json
  packages/themes/default/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
  publiccode.yml
  scripts/update-publiccode.mjs
Labels: v1

#6618 Component synonyms for readme's
  packages/components/src/components/accordion/readme.md
  packages/components/src/components/alert/readme.md
  packages/components/src/components/avatar/readme.md
  packages/components/src/components/combobox/readme.md
  packages/components/src/components/details/readme.md
  packages/components/src/components/drawer/readme.md
  packages/components/src/components/image/readme.md
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/input-file/readme.md
  packages/components/src/components/input-radio/readme.md
  packages/components/src/components/input-range/readme.md
  packages/components/src/components/input-text/readme.md
  packages/components/src/components/modal/readme.md
  packages/components/src/components/nav/readme.md
  packages/components/src/components/select/readme.md
  packages/components/src/components/spin/readme.md
  packages/components/src/components/table-stateful/readme.md
  packages/components/src/components/table-stateless/readme.md
  packages/components/src/components/table/readme.md
  packages/components/src/components/tabs/readme.md
  packages/components/src/components/toaster/readme.md
  packages/components/src/components/tooltip/readme.md
  packages/components/src/components/tree/readme.md
Labels: doc, v2

#6624 Update "update snapshots" workflow: Commit using custom App user instead of GH Bot
  .github/workflows/update-snapshots.yml
Labels: v1

#6625 Update "update snapshots" workflow: Commit using custom App user instead of GH Bot
  .github/workflows/update-snapshots.yml
Labels: v2

#6634 Expansion table selection
  packages/components/src/components/table-stateless/component.tsx
  packages/components/src/i18n.ts
  packages/components/src/locales/de.ts
  packages/components/src/locales/en.ts
Labels: feature, v2

#6664 Configure Publish workflow to use GitHub app
  .github/workflows/publish.yml
Labels: v2

#6663 Publish Workflow: Use GitHub App User
  .github/workflows/publish.yml
Labels: v1

#6671 Configure npm provenance
  .github/workflows/publish.yml
  packages/components/package.json
  packages/components/scripts/anonymous.js
  packages/samples/react/package.json
Labels: v2

#6677 Configure npm provenance
  .github/workflows/publish.yml
  packages/components/scripts/anonymous.js
  packages/samples/react/package.json
Labels: v1

#6686 Fix create-kolibri
  packages/create-kolibri/package.json
  packages/create-kolibri/src/index.ts
Labels: v1
