Repository public-ui/kolibri, pull requests merged in 2024-05, with the labels that each got.

#6326 Submit form on enter for select and radio; Fix radio form association
  packages/components/src/components/input-adapter-leanup/associated.controller.ts
  packages/components/src/components/input-radio/component.tsx
  packages/components/src/components/select/component.tsx
Labels: v2

#6399 6398 remove bstw and add missing scripts
  packages/samples/react/src/shares/theme.ts
  packages/themes/bmf/package.json
  packages/themes/bstw/.eslintrc.cjs
  packages/themes/bstw/LICENSE
  packages/themes/bstw/README.md
  packages/themes/bstw/package.json
  packages/themes/bstw/rollup.config.js
  packages/themes/bstw/src/components/abbr.scss
  packages/themes/bstw/src/components/accordion.scss
  packages/themes/bstw/src/components/alert.scss
  packages/themes/bstw/src/components/avatar.scss
  packages/themes/bstw/src/components/badge.scss
  packages/themes/bstw/src/components/breadcrumb.scss
  packages/themes/bstw/src/components/button-group.scss
  packages/themes/bstw/src/components/button-link.scss
  packages/themes/bstw/src/components/button.scss
  packages/themes/bstw/src/components/card.scss
  packages/themes/bstw/src/components/details.scss
  packages/themes/bstw/src/components/heading.scss
  packages/themes/bstw/src/components/icon.scss
  packages/themes/bstw/src/components/indented-text.scss
  packages/themes/bstw/src/components/input-checkbox.scss
  packages/themes/bstw/src/components/input-color.scss
  packages/themes/bstw/src/components/input-date.scss
  packages/themes/bstw/src/components/input-email.scss
  packages/themes/bstw/src/components/input-file.scss
  packages/themes/bstw/src/components/input-number.scss
  packages/themes/bstw/src/components/input-password.scss
  packages/themes/bstw/src/components/input-radio.scss
  packages/themes/bstw/src/components/input-range.scss
  packages/themes/bstw/src/components/input-text.scss
  packages/themes/bstw/src/components/kolibri.scss
  packages/themes/bstw/src/components/link-button.scss
  packages/themes/bstw/src/components/link.scss
  packages/themes/bstw/src/components/modal.scss
  packages/themes/bstw/src/components/nav.scss
  packages/themes/bstw/src/components/pagination.scss
  packages/themes/bstw/src/components/progress.scss
  packages/themes/bstw/src/components/select.scss
  packages/themes/bstw/src/components/skip-nav.scss
  packages/themes/bstw/src/components/split-button.scss
  packages/themes/bstw/src/components/table-stateful.scss
  packages/themes/bstw/src/components/table-stateless.scss
  packages/themes/bstw/src/components/tabs.scss
  packages/themes/bstw/src/components/textarea.scss
  packages/themes/bstw/src/components/toast-container.scss
  packages/themes/bstw/src/components/tree-item.scss
  packages/themes/bstw/src/components/tree.scss
  packages/themes/bstw/src/global.scss
  packages/themes/bstw/src/globals.d.ts
  packages/themes/bstw/src/index.ts
  packages/themes/bstw/src/mixins/alert-wc.scss
  packages/themes/bstw/src/mixins/button.scss
  packages/themes/bstw/src/mixins/focus-outline.scss
  packages/themes/bstw/tsconfig.json
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
  packages/themes/src/index.ts
Labels: v2

#6404 6351 add enginge and package manager
  .github/workflows/cla.yml
  package.json
Labels: v1

#6403 chore: add engine configuration
  package.json
Labels: v2

#6414 Fixed ITZ theme table border style
  packages/themes/itzbund/src/components/table.scss
Labels: bug, v1

#6409 Fixed ITZ theme table border style
  packages/themes/itzbund/src/components/table-stateless.scss
Labels: bug, do not merge, v2

#6259 Test: Creation of tests for previously untested components
  packages/components/src/components/link-button/component.tsx
  packages/components/src/components/link-button/readme.md
  packages/components/src/components/link-button/test/html.mock.ts
  packages/components/src/components/link-button/test/snapshot.spec.tsx
  packages/components/src/components/link-group/test/html.mock.ts
  packages/components/src/components/link-group/test/snapshot.spec.tsx
  packages/components/src/components/modal/test/html.mock.ts
  packages/components/src/components/modal/test/snapshot.spec.tsx
  packages/components/src/components/nav/test/html.mock.ts
  packages/components/src/components/nav/test/snapshot.spec.tsx
  packages/components/src/components/pagination/test/html.mock.ts
  packages/components/src/components/pagination/test/snapshot.spec.tsx
  packages/components/src/components/select/test/html.mock.ts
  packages/components/src/components/select/test/snapshot.spec.tsx
  packages/components/src/components/skip-nav/test/html.mock.ts
  packages/components/src/components/skip-nav/test/snapshot.spec.tsx
  packages/components/src/components/split-button/component.tsx
  packages/components/src/components/split-button/test/html.mock.ts
  packages/components/src/components/split-button/test/snapshot.spec.tsx
  packages/components/src/components/tabs/test/html.mock.ts
  packages/components/src/components/tabs/test/snapshot.spec.tsx
  packages/components/src/components/textarea/test/html.mock.ts
  packages/components/src/components/textarea/test/snapshot.spec.tsx
  packages/components/src/schema/components/select.ts
  packages/components/src/schema/components/split-button.ts
  packages/components/src/schema/components/textarea.ts
  packages/components/stencil.config.ts
  packages/components/test-env.js
  pnpm-lock.yaml
Labels: re-review

#6429 Bugfix table sorting button style (font-weight)
  packages/components/src/components/table-stateless/style.scss
Labels: bug, v2

#6394 refact: initialize i18n Service before first translation if not happened
  packages/components/src/core/i18n.ts
  packages/components/src/i18n.ts
Labels: re-review

#6432 Bugfix table sorting button style (font-weight)
  packages/components/src/components/table-stateless/style.scss
  packages/themes/default/src/components/table-stateless.scss
  packages/themes/ecl/src/components/ecl-ec/table-stateless.scss
  packages/themes/ecl/src/components/ecl-eu/table-stateless.scss
Labels: bug, v2

#6406 Adjust input field behavior to keep placeholder text visible
  packages/components/src/components/input-password/controller.ts
Labels: a11y-retest

#6389 Implement selection feature for TableStateless
  packages/components/src/components/table-stateless/component.tsx
  packages/components/src/components/table-stateless/readme.md
  packages/components/src/components/table-stateless/shadow.tsx
  packages/components/src/components/table-stateless/style.scss
  packages/components/src/index.ts
  packages/components/src/schema/components/tableStateless.ts
  packages/components/src/schema/enums/events.ts
  packages/components/src/schema/props/index.ts
  packages/components/src/schema/props/table-callbacks.ts
  packages/components/src/schema/props/table-selection.ts
  packages/components/src/schema/types/table.ts
  packages/components/src/utils/events.ts
  packages/samples/react/src/components/table/routes.ts
  packages/samples/react/src/components/table/stateless-with-selection.tsx
Labels: a11y-retest, v2, re-review

#6463 (#6428) chore: remove dod check and add documentation
  .github/dod.yml
  .github/workflows/dod-checker.yml
  docs/DoD.md
Labels: v1

#6458 Fix: Designer an neues Theming-Handling-Anbindung
  packages/designer/src/components/app/component.solid.tsx
  packages/designer/src/components/editor/store.tsx
  packages/designer/src/components/editor/ts-editor.ts
Labels: v2

#6466 fix: remove unused code for placeholder handling
  packages/components/src/components/input-password/controller.ts
Labels: v2

#6465 fix: remove unused code for placeholder handling
  packages/components/src/components/input-password/controller.ts
Labels: v1

#6354 Component: Conversion of the ComboBox
  packages/components/src/components/combobox/controller.ts
  packages/components/src/components/combobox/readme.md
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/combobox/style.scss
  packages/components/src/components/component-list.ts
  packages/components/src/locales/de.ts
  packages/components/src/locales/en.ts
  packages/components/src/schema/components/combobox.ts
  packages/components/src/schema/components/index.ts
  packages/components/src/schema/tag-names.ts
  packages/samples/react/src/components/combobox/basic.tsx
  packages/samples/react/src/components/combobox/partials/cases.tsx
  packages/samples/react/src/components/combobox/partials/variants.tsx
  packages/samples/react/src/components/combobox/routes.ts
  packages/samples/react/src/components/select/partials/cases.tsx
  packages/samples/react/src/shares/country.ts
  packages/samples/react/src/shares/routes.ts
  packages/themes/bmf/src/components/combobox.scss
  packages/themes/bmf/src/index.ts
  packages/themes/default/src/components/combobox.scss
  packages/themes/default/src/index.ts
  packages/themes/ecl/src/components/ecl-ec/combobox.scss
  packages/themes/ecl/src/components/ecl-eu/combobox.scss
  packages/themes/ecl/src/ecl-ec.ts
  packages/themes/ecl/src/ecl-eu.ts
  packages/themes/itzbund/src/components/combobox.scss
  packages/themes/itzbund/src/index.ts
  pnpm-lock.yaml
Labels: v2, re-review

#6468 build: monorepo für pnpm 9 anpassen
  .github/workflows/auto-dependency-updater.yml
  .github/workflows/auto-file-generator.yml
  .github/workflows/ci.yml
  .github/workflows/draft-deploy.yml
  .github/workflows/publish.yml
  .github/workflows/test-deploy.yml
  .github/workflows/update-snapshots.yml
  .npmrc
  package.json
  packages/adapters/angular/v11/package.json
  packages/adapters/angular/v12/package.json
  packages/adapters/angular/v13/package.json
  packages/adapters/angular/v14/package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/hydrate/package.json
  packages/adapters/preact/package.json
  packages/adapters/react-standalone/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/adapters/vue/package.json
  packages/components/src/components/input-checkbox/readme.md
  packages/components/src/components/input-color/readme.md
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/input-email/readme.md
  packages/components/src/components/input-file/readme.md
  packages/components/src/components/input-number/readme.md
  packages/components/src/components/input-password/readme.md
  packages/components/src/components/input-radio/readme.md
  packages/components/src/components/input-range/readme.md
  packages/components/src/components/input-text/readme.md
  packages/components/src/components/select/readme.md
  packages/components/src/components/textarea/readme.md
  packages/components/src/components/toaster/readme.md
  packages/designer/package.json
  packages/samples/angular/package.json
  packages/samples/react/package.json
  packages/storybook/package.json
  packages/themes/bmf/package.json
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v2

#6405 Implementation of Toolbar component
  packages/components/src/components/component-list.ts
  packages/components/src/components/toolbar/readme.md
  packages/components/src/components/toolbar/shadow.tsx
  packages/components/src/components/toolbar/style.scss
  packages/components/src/components/toolbar/test/html.mock.ts
  packages/components/src/components/toolbar/test/snapshot.spec.tsx
  packages/components/src/core/component-names.ts
  packages/components/src/schema/components/index.ts
  packages/components/src/schema/components/toolbar.ts
  packages/components/src/schema/props/index.ts
  packages/components/src/schema/props/toolbar-items.ts
  packages/components/stencil.config.ts
  packages/samples/react/src/components/toolbar/basic.tsx
  packages/samples/react/src/components/toolbar/disabled.tsx
  packages/samples/react/src/components/toolbar/routes.ts
  packages/samples/react/src/shares/routes.ts
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-toolbar-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-toolbar-disabled-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-toolbar-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-toolbar-disabled-firefox-linux.png
  packages/themes/bmf/src/components/toolbar.scss
  packages/themes/bmf/src/index.ts
  packages/themes/default/snapshots/theme-default/snapshot-for-table-stateless-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-toolbar-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-toolbar-disabled-firefox-linux.png
  packages/themes/default/src/components/toolbar.scss
  packages/themes/default/src/index.ts
  packages/themes/ecl/src/components/ecl-ec/toolbar.scss
  packages/themes/ecl/src/components/ecl-eu/toolbar.scss
  packages/themes/ecl/src/ecl-ec.ts
  packages/themes/ecl/src/ecl-eu.ts
  packages/themes/itzbund/src/components/toolbar.scss
  packages/themes/itzbund/src/index.ts
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: v2, re-review

#6306 fixed textarea scrollbar issue
  packages/components/src/components/textarea/shadow.tsx
Labels: do not merge

#6419 chore: update dependencies and lock file
  packages/adapters/angular/v11/package.json
  packages/adapters/angular/v12/package.json
  packages/adapters/angular/v13/package.json
  packages/adapters/angular/v14/package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/hydrate/package.json
  packages/adapters/preact/package.json
  packages/adapters/react-standalone/package.json
  packages/adapters/react/package.json
  packages/adapters/vue/package.json
  packages/components/package.json
  packages/create-kolibri/package.json
  packages/designer/package.json
  packages/samples/angular/package.json
  packages/samples/react/package.json
  packages/themes/bmf/package.json
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v2

#6418 chore: update dependencies and lock file
  packages/adapters/angular/v11/package.json
  packages/adapters/angular/v12/package.json
  packages/adapters/angular/v13/package.json
  packages/adapters/angular/v14/package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/hydrate/package.json
  packages/adapters/preact/package.json
  packages/adapters/react-standalone/package.json
  packages/adapters/react/package.json
  packages/adapters/vue/package.json
  packages/components/package.json
  packages/core/package.json
  packages/create-kolibri/package.json
  packages/designer/package.json
  packages/samples/react/package.json
  packages/schema/package.json
  packages/themes/default/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v1

#6473 fix: selects onChange event is only raised when the value has changed, and not initially
  packages/components/src/components/combobox/readme.md
  packages/components/src/components/input-checkbox/readme.md
  packages/components/src/components/input-color/readme.md
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/input-email/readme.md
  packages/components/src/components/input-file/readme.md
  packages/components/src/components/input-number/readme.md
  packages/components/src/components/input-password/readme.md
  packages/components/src/components/input-radio/readme.md
  packages/components/src/components/input-range/readme.md
  packages/components/src/components/input-text/readme.md
  packages/components/src/components/select/controller.ts
  packages/components/src/components/select/readme.md
  packages/components/src/components/select/shadow.tsx
  packages/components/src/components/textarea/readme.md
  packages/components/src/components/toaster/readme.md
  packages/samples/react/src/components/Sidebar.tsx
Labels: bug, v2

#6415 Implement missing keyboard shortcuts for tree navigation
  packages/components/src/components/tree/component.tsx
Labels: a11y-retest

#6480 6198 bug designer funktioniert nicht mehr
  packages/components/package.json
  packages/components/src/schema/utils/prop.validators.ts
  packages/designer/package.json
  packages/designer/public/index.html
  packages/designer/src/components/app/component.solid.tsx
  packages/designer/src/components/editor/css-style.editor.ts
  packages/designer/src/shares/theme.ts
  pnpm-lock.yaml
Labels: v2
