Repository public-ui/kolibri, pull requests merged in 2024-09, with the labels that each got.

#6736 sampe formatting options for input fields
  packages/samples/react/src/components/input-text/routes.ts
  packages/samples/react/src/components/input-text/text-formatter.tsx
Labels: nok

#6751 docs: update snapshot workflow doc
  CONTRIBUTING.md
Labels: v2, nok

#6709 chore: update deps and lock
  package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/hydrate/package.json
  packages/adapters/preact/package.json
  packages/adapters/react-standalone/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/adapters/vue/package.json
  packages/components/package.json
  packages/components/src/components/accordion/test/html.mock.ts
  packages/components/src/components/accordion/test/snapshot.spec.tsx
  packages/components/src/components/card/test/html.mock.ts
  packages/components/src/components/card/test/snapshot.spec.tsx
  packages/components/src/components/icon-font-awesome/readme.md
  packages/components/src/components/icon-icofont/readme.md
  packages/components/src/components/tabs/readme.md
  packages/core/package.json
  packages/create-kolibri/package.json
  packages/designer/package.json
  packages/samples/react/package.json
  packages/schema/package.json
  packages/themes/bmf/package.json
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v1

#6754 switch option label alignment
  packages/components/src/components/input-checkbox/button.scss
  packages/components/src/components/input-checkbox/common.scss
  packages/components/src/components/input-checkbox/controller.ts
  packages/components/src/components/input-checkbox/readme.md
  packages/components/src/components/input-checkbox/shadow.tsx
  packages/components/src/components/input-checkbox/test/html.mock.ts
  packages/components/src/components/input-checkbox/test/snapshot.spec.tsx
  packages/components/src/schema/components/input-checkbox.ts
  packages/components/src/schema/props/index.ts
  packages/components/src/schema/props/label-align.ts
  packages/samples/react/src/components/input-checkbox/partials/variants.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-basic-label-align-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-button-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-button-label-align-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-switch-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-switch-label-align-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-basic-label-align-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-button-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-button-label-align-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-switch-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-switch-label-align-firefox-linux.png
  packages/themes/bmf/src/components/input-checkbox.scss
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-basic-label-align-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-button-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-button-label-align-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-switch-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-switch-label-align-firefox-linux.png
  packages/themes/default/src/components/input-checkbox.scss
  packages/themes/ecl/src/components/ecl-ec/input-checkbox.scss
  packages/themes/ecl/src/components/ecl-eu/input-checkbox.scss
  packages/themes/itzbund/src/components/input-checkbox.scss
Labels: nok

#6792 chore: update dependencies and lock file
  lerna.json
  package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/angular/v18/package.json
  packages/adapters/preact/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/adapters/vue/package.json
  packages/components/.eslintrc.js
  packages/components/package.json
  packages/components/src/components/pagination/test/html.mock.ts
  packages/components/src/components/tabs/readme.md
  packages/components/src/declare.d.ts
  packages/components/src/index.ts
  packages/components/tsconfig.json
  packages/create-kolibri/.editorconfig
  packages/create-kolibri/.eslintrc.cjs
  packages/create-kolibri/.gitignore
  packages/create-kolibri/.knip.json
  packages/create-kolibri/.prettierignore
  packages/create-kolibri/LICENSE
  packages/create-kolibri/README.md
  packages/create-kolibri/package.json
  packages/create-kolibri/prettier.config.js
  packages/create-kolibri/src/index.ts
  packages/create-kolibri/tsconfig.json
  packages/create-kolibri/tsup.config.ts
  packages/designer/.eslintrc.js
  packages/designer/package.json
  packages/designer/tsconfig.json
  packages/samples/angular/package.json
  packages/samples/angular/tsconfig.app.json
  packages/samples/angular/tsconfig.spec.json
  packages/samples/react/package.json
  packages/samples/react/src/components/table/interactive-child-elements.tsx
  packages/samples/react/tsconfig.json
  packages/themes/.eslintrc.cjs
  packages/themes/bmf/package.json
  packages/themes/default/.eslintrc.cjs
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/.eslintrc.cjs
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/.eslintrc.cjs
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  publiccode.yml
  scripts/deprecate-add.sh
  scripts/deprecate-rm.sh
  scripts/license-reports.sh
Labels: v2

#6791 chore: update dependencies and lock file
  lerna.json
  package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/preact/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/adapters/vue/package.json
  packages/components/.eslintrc.js
  packages/components/package.json
  packages/components/src/components/toast/toaster.tsx
  packages/components/tsconfig.json
  packages/core/.eslintrc.cjs
  packages/core/package.json
  packages/core/tsconfig.json
  packages/create-kolibri/.editorconfig
  packages/create-kolibri/.eslintrc.cjs
  packages/create-kolibri/.gitignore
  packages/create-kolibri/.knip.json
  packages/create-kolibri/.prettierignore
  packages/create-kolibri/LICENSE
  packages/create-kolibri/README.md
  packages/create-kolibri/package.json
  packages/create-kolibri/prettier.config.js
  packages/create-kolibri/src/index.ts
  packages/create-kolibri/tsconfig.json
  packages/create-kolibri/tsup.config.ts
  packages/designer/.eslintrc.js
  packages/designer/package.json
  packages/designer/tsconfig.json
  packages/samples/react/package.json
  packages/samples/react/tsconfig.json
  packages/schema/.eslintrc.cjs
  packages/schema/package.json
  packages/storybook/tsconfig.json
  packages/themes/.eslintrc.cjs
  packages/themes/bmf/package.json
  packages/themes/default/.eslintrc.cjs
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/.eslintrc.cjs
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/.eslintrc.cjs
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/deprecate-add.sh
  scripts/deprecate-rm.sh
  scripts/license-reports.sh
Labels: v1
