Repository public-ui/kolibri, pull requests merged in 2024-03, with the labels that each got.

#6107 fix: condition to register kolibri once
  packages/components/src/components/modal/component.tsx
  packages/components/src/core/bootstrap.ts
  packages/components/src/core/i18n.ts
  packages/components/src/core/index.ts
  packages/components/src/global/devtools.ts
  packages/components/src/global/script.ts
  packages/components/src/i18n.ts
  packages/components/src/index.ts
  packages/components/src/utils/dev.utils.ts
  packages/samples/react/src/react.main.tsx
Labels: v2

#6152 refactor: remove Modal and I18n from Window
  packages/components/src/components/modal/component.tsx
  packages/components/src/core/bootstrap.ts
  packages/components/src/core/i18n.ts
  packages/components/src/global/devtools.ts
  packages/components/src/global/script.ts
  packages/components/src/i18n.ts
  packages/components/src/index.ts
  packages/components/src/utils/dev.utils.ts
  packages/samples/react/src/react.main.tsx
Labels: v1

#6150 Input components: Change keyup to keydown event in order to prevent accidental form submissions
  packages/components/src/components/badge/readme.md
  packages/components/src/components/input-color/readme.md
  packages/components/src/components/input-date/component.tsx
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/input-email/component.tsx
  packages/components/src/components/input-email/readme.md
  packages/components/src/components/input-file/readme.md
  packages/components/src/components/input-number/component.tsx
  packages/components/src/components/input-number/readme.md
  packages/components/src/components/input-password/component.tsx
  packages/components/src/components/input-password/readme.md
  packages/components/src/components/input-range/component.tsx
  packages/components/src/components/input-text/component.tsx
  packages/components/src/components/input-text/readme.md
  packages/samples/react/src/scenarios/static-form.tsx
Labels: v2

#6154 chore: update deps and lock
  package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/react/package.json
  packages/adapters/vue/package.json
  packages/components/package.json
  packages/core/package.json
  packages/create-kolibri/templates/angular-app/package.json
  packages/create-kolibri/templates/astro-app/package.json
  packages/create-kolibri/templates/kolibri-library/package.json
  packages/create-kolibri/templates/preact-app/package.json
  packages/create-kolibri/templates/react-app/package.json
  packages/create-kolibri/templates/solid-app/package.json
  packages/create-kolibri/templates/vue-app/package.json
  packages/designer/package.json
  packages/samples/react/package.json
  packages/schema/package.json
  packages/themes/default/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v1

#6172 Refactor v2/remove kolibri and logo from theming
  packages/schema/src/tag-names.ts
  packages/themes/bmf/src/components/kolibri.scss
  packages/themes/bmf/src/index.ts
  packages/themes/default/src/components/kolibri.scss
  packages/themes/default/src/index.ts
  packages/themes/ecl/src/components/ecl-ec/kolibri.scss
  packages/themes/ecl/src/components/ecl-eu/kolibri.scss
  packages/themes/ecl/src/ecl-ec.ts
  packages/themes/ecl/src/ecl-eu.ts
  packages/themes/itzbund/src/components/kolibri.scss
Labels: v2

#6092 Set focus to error list on form submission
  packages/components/src/components/form/component.tsx
  packages/components/src/components/form/readme.md
  packages/components/src/components/icon-font-awesome/readme.md
  packages/components/src/components/icon-icofont/readme.md
  packages/samples/react/src/scenarios/appointment-form/AppointmentForm.tsx
  packages/samples/react/src/scenarios/appointment-form/AvailableAppointmentsForm.tsx
  packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
  packages/samples/react/src/scenarios/appointment-form/PersonalInformationForm.tsx
  packages/samples/react/src/scenarios/appointment-form/formUtils.ts
Labels: a11y-retest, v1

#6185 Components: Introduce mixin for rem values which can be configured at runtime
  packages/components/src/components/@shared/_mixins.scss
  packages/components/src/components/avatar/style.scss
  packages/components/src/components/icon-font-awesome/readme.md
  packages/components/src/components/icon-icofont/readme.md
  packages/components/src/components/input-range/style.scss
  packages/components/src/components/input.scss
  packages/components/src/components/link-group/style.scss
  packages/components/src/components/spin/cycle.scss
  packages/components/src/components/spin/dot.scss
  packages/components/src/components/spin/style.scss
  packages/components/src/components/tabs/readme.md
Labels: v1

#6187 Components: Introduce mixin for rem values which can be configured at runtime
  packages/components/src/components/@shared/_kol-alert-mixin.scss
  packages/components/src/components/@shared/_mixins.scss
  packages/components/src/components/avatar/style.scss
  packages/components/src/components/input-range/style.scss
  packages/components/src/components/input.scss
  packages/components/src/components/link-group/style.scss
  packages/components/src/components/pagination/style.scss
  packages/components/src/components/spin/cycle.scss
  packages/components/src/components/spin/dot.scss
  packages/components/src/components/spin/style.scss
Labels: v2

#6194 fix: dod pipeline concurrency mode handling
  .github/dod.yml
  .github/workflows/auto-dependency-updater.yml
  .github/workflows/auto-file-generator.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/dod-checker.yml
  .github/workflows/publish-page.yml
  .github/workflows/publish.yml
  .github/workflows/stale.yml
  .github/workflows/update-snapshots.yml
Labels: v1

#6215 Optimize peer dependency handling
  .ncurc.json
  .npmrc
  package.json
  packages/adapters/angular/v11/package.json
  packages/adapters/angular/v12/package.json
  packages/adapters/angular/v13/package.json
  packages/adapters/angular/v14/package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/preact/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/components/package.json
  packages/create-kolibri/package.json
  packages/designer/package.json
  packages/samples/react/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v1

#6213 Optimize peer dependency handling
  .ncurc.json
  .npmrc
  package.json
  packages/adapters/angular/v11/package.json
  packages/adapters/angular/v12/package.json
  packages/adapters/angular/v13/package.json
  packages/adapters/angular/v14/package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/preact/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/components/package.json
  packages/create-kolibri/package.json
  packages/designer/package.json
  packages/samples/react/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v2

#6220 Ng/add angular app sample
  packages/adapters/angular/v17/package.json
  packages/samples/angular/.gitignore
  packages/samples/angular/.vscode/extensions.json
  packages/samples/angular/.vscode/launch.json
  packages/samples/angular/.vscode/tasks.json
  packages/samples/angular/README.md
  packages/samples/angular/angular.json
  packages/samples/angular/package-lock.json
  packages/samples/angular/package.json
  packages/samples/angular/src/app/app.component.html
  packages/samples/angular/src/app/app.component.scss
  packages/samples/angular/src/app/app.component.spec.ts
  packages/samples/angular/src/app/app.component.ts
  packages/samples/angular/src/app/app.config.ts
  packages/samples/angular/src/app/app.routes.ts
  packages/samples/angular/src/assets/.gitkeep
  packages/samples/angular/src/favicon.ico
  packages/samples/angular/src/index.html
  packages/samples/angular/src/main.ts
  packages/samples/angular/src/styles.scss
  packages/samples/angular/tsconfig.app.json
  packages/samples/angular/tsconfig.json
  packages/samples/angular/tsconfig.spec.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: v2

#6226 Refactor: Remove `complex-form` and Resolve Focus Issue in `appointment-form`
  packages/components/package.json
  packages/components/scripts/autogen.doc.js
  packages/components/src/components/form/component.tsx
  packages/samples/react/src/scenarios/complex-form/common/form/component.tsx
  packages/samples/react/src/scenarios/complex-form/common/form/types.ts
  packages/samples/react/src/scenarios/complex-form/component.tsx
  packages/samples/react/src/scenarios/complex-form/kopfdaten/component.tsx
  packages/samples/react/src/scenarios/complex-form/location/component.tsx
  packages/samples/react/src/scenarios/complex-form/location/location.form.ts
  packages/samples/react/src/scenarios/complex-form/schedule/component.tsx
  packages/samples/react/src/scenarios/complex-form/schedule/schedule.form.ts
  packages/samples/react/src/scenarios/routes.ts
Labels: a11y-retest, v1

#6230 Fix mouse events within tables
  packages/components/src/components/table/component.tsx
Labels: v2

#6231 Fix mouse events within tables
  packages/components/src/components/table/component.tsx
Labels: v1

#6203 BMF theme input variant checkbox: Add hover style and extend clickable area
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-button-firefox-linux.png
  packages/themes/bmf/src/components/input-checkbox.scss
Labels: desybri, v2

#6244 Update DoD
  .github/dod.yml
Labels: v1

#6199 Update KolInputRadio value type to unknown and add example with object as value in React sample app
  packages/components/src/components/input-radio/component.tsx
  packages/components/src/components/input-radio/controller.ts
  packages/samples/react/src/components/input-radio/objectValue.tsx
  packages/samples/react/src/components/input-radio/routes.ts
  packages/schema/src/components/input-radio.ts
  packages/schema/src/props/options.ts
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: v2

#6209 Remove `nav` tag and make `_label` optional in KolLinkGroup
  packages/components/src/components/link-group/component.tsx
  packages/components/src/components/link-group/readme.md
  packages/components/src/components/link-group/style.scss
  packages/schema/src/components/link-group.ts
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-split-button-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-range-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-kolibri-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-complex-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-spin-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-password-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-complex-form-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-spin-basic-firefox-linux.png
Labels: a11y-retest

#6243 Update GitHub workflows
  .github/dod.yml
  .github/workflows/ci.yml
Labels: v1

#6235 Add new helper function `createReactRenderElement`
  packages/adapters/react/build.config.ts
  packages/adapters/react/kolibri-src/create-react-render-element.ts
  packages/adapters/react/kolibri-src/index.ts
  packages/components/src/components/table/readme.md
  packages/samples/react/src/components/table/render-cell.tsx
  packages/samples/react/src/shares/react-roots.ts
Labels: v1

#6247 Normalize change and input events across all input components
  packages/components/src/components/@deprecated/input/controller.ts
  packages/components/src/components/badge/readme.md
  packages/components/src/components/input-checkbox/component.tsx
  packages/components/src/components/input-checkbox/readme.md
  packages/components/src/components/input-color/readme.md
  packages/components/src/components/input-date/component.tsx
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/input-email/component.tsx
  packages/components/src/components/input-email/readme.md
  packages/components/src/components/input-file/component.tsx
  packages/components/src/components/input-file/readme.md
  packages/components/src/components/input-number/component.tsx
  packages/components/src/components/input-number/readme.md
  packages/components/src/components/input-password/component.tsx
  packages/components/src/components/input-password/readme.md
  packages/components/src/components/input-radio/readme.md
  packages/components/src/components/input-range/component.tsx
  packages/components/src/components/input-range/readme.md
  packages/components/src/components/input-text/component.tsx
  packages/components/src/components/input-text/readme.md
  packages/components/src/components/select/component.tsx
  packages/components/src/components/select/readme.md
  packages/components/src/components/textarea/component.tsx
  packages/components/src/components/textarea/readme.md
  packages/components/src/utils/events.ts
  packages/samples/angular/angular.json
  packages/schema/src/types/input/types.ts
Labels: v2

#6248 Add new helper function `createReactRenderElement`
  packages/adapters/react/build.config.ts
  packages/adapters/react/kolibri-src/create-react-render-element.ts
  packages/adapters/react/kolibri-src/index.ts
  packages/components/src/components/badge/readme.md
  packages/components/src/components/input-color/readme.md
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/input-email/readme.md
  packages/components/src/components/input-file/readme.md
  packages/components/src/components/input-number/readme.md
  packages/components/src/components/input-password/readme.md
  packages/components/src/components/input-text/readme.md
  packages/components/src/components/table/readme.md
  packages/samples/react/src/components/table/render-cell.tsx
  packages/samples/react/src/shares/react-roots.ts
Labels: v2

#6238 Progress bar: Allow dynamic SVG width, refactor, make <text> part of the SVG
  packages/components/src/components/progress/component.tsx
  packages/components/src/components/progress/style.scss
  packages/components/src/components/progress/test/snapshot.spec.tsx
  packages/samples/react/src/components/progress/basic.tsx
  packages/schema/src/types/progress.ts
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-progress-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-complex-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-progress-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-progress-basic-firefox-linux.png
  packages/themes/itzbund/src/components/progress.scss
Labels: v2

#6264 Include development modules only in development mode.
  packages/components/src/components/icon-font-awesome/readme.md
  packages/components/src/components/icon-icofont/readme.md
  packages/components/src/components/tabs/readme.md
  packages/components/src/global/script.ts
  packages/components/stencil.config.ts
Labels: v1

#6266 Add missing CommonModule import to Angular modules
  packages/adapters/angular/v13/ng-module.js
  packages/adapters/angular/v14/ng-module.js
  packages/adapters/angular/v15/ng-module.js
  packages/adapters/angular/v16/ng-module.js
  packages/adapters/angular/v17/ng-module.js
Labels: v1

#6267 Add missing CommonModule import to Angular modules
  packages/adapters/angular/v13/ng-module.js
  packages/adapters/angular/v14/ng-module.js
  packages/adapters/angular/v15/ng-module.js
  packages/adapters/angular/v16/ng-module.js
  packages/adapters/angular/v17/ng-module.js
Labels: v2
