Repository public-ui/kolibri, pull requests merged in 2024-08, with the labels that each got.

#6621 Improvements combobox component
  packages/components/src/components/combobox/readme.md
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/combobox/style.scss
  packages/components/src/components/input-adapter-leanup/associated.controller.ts
  packages/components/src/components/input-checkbox/readme.md
  packages/components/src/components/input-color/readme.md
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/input-email/readme.md
  packages/components/src/components/input-file/readme.md
  packages/components/src/components/input-number/readme.md
  packages/components/src/components/input-password/readme.md
  packages/components/src/components/input-radio/readme.md
  packages/components/src/components/input-range/readme.md
  packages/components/src/components/input-text/readme.md
  packages/components/src/components/select/readme.md
  packages/components/src/components/textarea/readme.md
  packages/components/src/components/toaster/readme.md
  packages/components/src/schema/components/input-password.ts
  packages/components/src/schema/utils/reuse.ts
  packages/samples/react/src/components/combobox/basic.tsx
  packages/samples/react/src/components/combobox/partials/cases.tsx
  packages/samples/react/src/components/combobox/partials/variants.tsx
  packages/samples/react/src/scenarios/focus-elements.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-combobox-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-combobox-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-combobox-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-focus-elements-component-combobox-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/bmf/src/components/combobox.scss
  packages/themes/default/snapshots/theme-default/snapshot-for-combobox-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-combobox-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/default/src/components/combobox.scss
  packages/themes/ecl/src/components/ecl-ec/combobox.scss
  packages/themes/ecl/src/components/ecl-eu/combobox.scss
  packages/themes/itzbund/src/components/combobox.scss
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: bug, v2

#6689 Integrate publish-page workflow into 'publish'
  .github/workflows/publish-page.yml
  .github/workflows/publish.yml
Labels: v1

#6694 refact: the hash code
  packages/samples/react/src/components/SampleDescription.tsx
Labels: v2

#6693 (#6652) refact: the hash code
  packages/samples/react/src/components/SampleDescription.tsx
Labels: v1

#6670 Add link to the sample code in the sample app
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/src/shares/constants.ts
Labels: v1

#6678 Add link to the sample code in the sample app
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/src/shares/constants.ts
Labels: v2

#6696 chore: update deps and lock
  package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/angular/v18/package.json
  packages/adapters/hydrate/package.json
  packages/adapters/preact/package.json
  packages/adapters/react-standalone/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/adapters/vue/package.json
  packages/components/package.json
  packages/components/src/components/quote/test/html.mock.ts
  packages/components/src/components/span/component.tsx
  packages/components/src/components/table-stateful/shadow.tsx
  packages/create-kolibri/package.json
  packages/designer/package.json
  packages/samples/angular/package.json
  packages/samples/react/package.json
  packages/themes/bmf/package.json
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v2

#6697 chore: update deps and lock
  packages/components/package.json
  packages/components/src/components/quote/test/html.mock.ts
  packages/components/src/components/table/component.tsx
Labels: v1

#6546 Implementation of SingleSelect with filter function
  packages/components/src/components/component-list.ts
  packages/components/src/components/input-adapter-leanup/associated.controller.ts
  packages/components/src/components/single-select/controller.ts
  packages/components/src/components/single-select/readme.md
  packages/components/src/components/single-select/shadow.tsx
  packages/components/src/components/single-select/style.scss
  packages/components/src/locales/de.ts
  packages/components/src/locales/en.ts
  packages/components/src/schema/components/index.ts
  packages/components/src/schema/components/single-select.ts
  packages/components/src/schema/tag-names.ts
  packages/samples/react/src/components/single-select/basic.tsx
  packages/samples/react/src/components/single-select/partials/cases.tsx
  packages/samples/react/src/components/single-select/partials/variants.tsx
  packages/samples/react/src/components/single-select/routes.ts
  packages/samples/react/src/scenarios/focus-elements.tsx
  packages/samples/react/src/scenarios/inputs-get-value.tsx
  packages/samples/react/src/scenarios/static-form.tsx
  packages/samples/react/src/shares/routes.ts
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-singleSelect-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-single-select-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-focus-elements-component-singleSelect-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-single-select-basic-firefox-linux.png
  packages/themes/bmf/src/components/single-select.scss
  packages/themes/bmf/src/index.ts
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-singleSelect-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-single-select-basic-firefox-linux.png
  packages/themes/default/src/components/single-select.scss
  packages/themes/default/src/index.ts
  packages/themes/ecl/src/components/ecl-ec/single-select.scss
  packages/themes/ecl/src/components/ecl-eu/single-select.scss
  packages/themes/ecl/src/ecl-ec.ts
  packages/themes/ecl/src/ecl-eu.ts
  packages/themes/itzbund/src/components/single-select.scss
  packages/themes/itzbund/src/index.ts
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: nok

#6701 Merge workflows publish and publish-page
  .github/workflows/publish-page.yml
  .github/workflows/publish.yml
Labels: v2

#6737 remove duplicate ids - associated Form-Fields
  packages/components/src/components/@deprecated/input/controller.ts
  packages/components/src/components/badge/readme.md
  packages/components/src/components/input-color/readme.md
  packages/components/src/components/input-date/readme.md
  packages/components/src/components/input-email/readme.md
  packages/components/src/components/input-file/readme.md
  packages/components/src/components/input-number/readme.md
  packages/components/src/components/input-password/readme.md
  packages/components/src/components/input-text/readme.md
Labels: nok

#6743 6341 - Snapshot branchauswahl vereinfachen
  .github/workflows/update-snapshots.yml
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-button-group-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-button-link-image-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-combobox-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-handout-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-color-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-email-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-password-show-password-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-link-image-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-nav-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-disabled-interactive-scenario-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-select-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-single-select-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tabs-icons-only-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-textarea-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-toolbar-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-toolbar-disabled-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-alert-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-alert-card-msg-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-button-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-button-group-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-button-link-image-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-button-width-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-combobox-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-form-error-list-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-handout-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-button-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-switch-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-color-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-date-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-email-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-file-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-number-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-password-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-password-show-password-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-radio-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-range-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-text-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-link-button-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-link-image-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-select-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-single-select-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-tabs-icons-only-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-textarea-basic-firefox-linux.png
Labels: v2

#6744 6341 - Snapshot branchauswahl vereinfachen
  .github/workflows/update-snapshots.yml
Labels: v1

#6695 Update input-radio with hint and description
  packages/components/src/components/input-radio/controller.ts
  packages/components/src/components/input-radio/readme.md
  packages/components/src/components/input-radio/shadow.tsx
  packages/components/src/components/input-radio/test/html.mock.ts
  packages/components/src/components/input-radio/test/snapshot.spec.tsx
  packages/components/src/schema/components/input-radio.ts
  packages/components/src/schema/props/options.ts
  packages/components/src/schema/types/input/types.ts
  packages/samples/react/src/components/input-radio/partials/cases.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-radio-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-radio-basic-firefox-linux.png
  packages/themes/bmf/src/components/input-radio.scss
  packages/themes/default/snapshots/theme-default/snapshot-for-input-radio-basic-firefox-linux.png
  packages/themes/default/src/components/input-radio.scss
  packages/themes/ecl/src/components/ecl-ec/input-radio.scss
  packages/themes/ecl/src/components/ecl-eu/input-radio.scss
  packages/themes/itzbund/src/components/input-radio.scss
Labels: nok

#6738 Migrations too replacel koltable to koltablestateful
  packages/tools/kolibri-cli/.kolibri.config.json
  packages/tools/kolibri-cli/src/migrate/runner/tasks/common/GenericRenameTagNameTask.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/common/RenameTagNameTask.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/v2/index.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/v2/table.ts
Labels: nok

#6734 Combobox unit test
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/combobox/test/html.mock.ts
  packages/components/src/components/combobox/test/snapshot.spec.tsx
  packages/components/src/schema/components/combobox.ts
Labels: nok
