Repository public-ui/kolibri, pull requests merged in 2024-02, with the labels that each got.

#5990 Fix new component tutorial
  .gitignore
  CONTRIBUTING.md
  docs/tutorials/NEW_COMPONENT.md
  docs/tutorials/new-component/component.tsx
  docs/tutorials/new-component/readme.md
  docs/tutorials/new-component/style.css
  docs/tutorials/new-component/test/html.mock.ts
  docs/tutorials/new-component/test/snapshot.spec.tsx
  docs/tutorials/new-component/types.ts
  packages/schema/src/index.ts
Labels: Do not merge!

#6011 Fix tooltips closing behaviour for Firefox ESR
  packages/components/src/components/tooltip/component.tsx
Labels: v2

#6007 Improve nav icon handling
  packages/components/src/components.d.ts
  packages/components/src/components/nav/component.tsx
  packages/samples/react/src/components/nav/basic.tsx
  packages/schema/src/components/nav.ts
  packages/schema/src/props/has-icons-when-expanded.ts
  packages/schema/src/props/index.ts
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-nav-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-horizontal-firefox-linux.png
Labels: v2

#4706 Tree component
  packages/components/src/components.d.ts
  packages/components/src/components/component-list.ts
  packages/components/src/components/link/readme.md
  packages/components/src/components/tree-item/component.tsx
  packages/components/src/components/tree-item/readme.md
  packages/components/src/components/tree-item/shadow.tsx
  packages/components/src/components/tree-item/style.css
  packages/components/src/components/tree/component.tsx
  packages/components/src/components/tree/constants.ts
  packages/components/src/components/tree/readme.md
  packages/components/src/components/tree/shadow.tsx
  packages/components/src/components/tree/style.css
  packages/components/src/dev.html
  packages/components/stencil.config.ts
  packages/components/tsconfig.json
  packages/samples/react/src/components/Sidebar.tsx
  packages/samples/react/src/components/tree/basic.tsx
  packages/samples/react/src/components/tree/routes.ts
  packages/samples/react/src/shares/randomEmoji.ts
  packages/samples/react/src/shares/routes.ts
  packages/schema/src/components/index.ts
  packages/schema/src/components/tree-item.ts
  packages/schema/src/components/tree.ts
  packages/schema/src/props/active.ts
  packages/schema/src/props/index.ts
  packages/schema/src/tag-names.ts
  packages/schema/src/types/input/control/number.ts
  packages/schema/src/types/input/types.ts
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tree-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tree-basic-home-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-tree-basic-home-firefox-linux.png
  packages/themes/default/src/components/tree-item.scss
  packages/themes/default/src/components/tree.scss
  packages/themes/default/src/index.ts
  packages/tools/visual-tests/tests/sample-app.routes.js
  pnpm-lock.yaml
Labels: v2

#6052 chore: upgrade github actions
  .github/dependabot.yml
  .github/workflows/auto-dependency-updater.yml
  .github/workflows/auto-file-generator.yml
  .github/workflows/ci.yml
  .github/workflows/cla.yml
  .github/workflows/draft-deploy.yml
  .github/workflows/publish.yml
  .github/workflows/test-deploy.yml
  .github/workflows/update-snapshots.yml
Labels: v2

#6053 chore: upgrade github actions
  .github/dependabot.yml
  .github/workflows/auto-dependency-updater.yml
  .github/workflows/auto-file-generator.yml
  .github/workflows/ci.yml
  .github/workflows/cla.yml
  .github/workflows/draft-deploy.yml
  .github/workflows/publish.yml
  .github/workflows/test-deploy.yml
Labels: v1

#5954 Hier ist noch die Nav okay...
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-accordion-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-accordion-headlines-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-accordion-list-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-alert-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-alert-card-msg-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-alert-html-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-breadcrumb-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-button-icons-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-details-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-handout-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-button-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-checkbox-switch-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-color-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-date-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-email-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-file-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-number-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-password-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-radio-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-radio-horizontal-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-range-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-text-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-pagination-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-appointment-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-complex-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-select-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-table-pagination-position-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-table-with-pagination-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tabs-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tabs-icons-only-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-textarea-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-textarea-with-counter-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tree-basic-firefox-linux.png
  packages/themes/bmf/src/index.ts
Labels: Do not merge!

#6065 fix: value sync for input radio
  packages/components/src/components/input-radio/controller.ts
  packages/components/src/components/select/controller.ts
Labels: bug, v2

#6066 fix: value sync for input radio
  packages/components/src/components/input-radio/controller.ts
  packages/components/src/components/select/controller.ts
Labels: bug, v1

#6034 5743 bug/appointment form focus issue
  packages/components/src/components/form/component.tsx
  packages/samples/react/src/scenarios/appointment-form/AppointmentForm.tsx
  packages/samples/react/src/scenarios/appointment-form/AvailableAppointmentsForm.tsx
  packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
  packages/samples/react/src/scenarios/appointment-form/ErrorList.tsx
  packages/samples/react/src/scenarios/appointment-form/PersonalInformationForm.tsx
  packages/samples/react/src/scenarios/appointment-form/formUtils.ts
Labels: a11y-retest, v1

#6049 Improve checkbox visibility with transparent border in forced color mode
  packages/themes/bmf/src/index.ts
  packages/themes/default/src/components/input-checkbox.scss
Labels: a11y-retest, v1

#6064 fix: experimental mode for static form handling
  package.json
  packages/components/src/components.d.ts
  packages/components/src/components/alert/component.tsx
  packages/components/src/components/form/controller.ts
  packages/components/src/components/input-adapter-leanup/associated.controller.ts
  packages/components/src/components/modal/service.ts
  packages/components/src/global/devtools.ts
  packages/components/src/global/script.ts
  packages/components/src/utils/dev.utils.ts
  packages/samples/library/README.md
  packages/samples/react/public/index.html
  packages/samples/react/src/scenarios/routes.ts
  packages/samples/react/src/scenarios/static-form.tsx
  packages/schema/src/utils/a11y.tipps.ts
  packages/schema/src/utils/dev.utils.ts
  packages/schema/src/utils/prop.validators.ts
  pnpm-lock.yaml
Labels: bug, v2

#6071 Fix/6063 experimental mode does not work v1
  packages/components/src/components/form/controller.ts
  packages/components/src/components/input-adapter-leanup/associated.controller.ts
  packages/samples/react/public/index.html
  packages/samples/react/src/scenarios/routes.ts
  packages/samples/react/src/scenarios/static-form.tsx
Labels: bug, v1

#6076 fix: use visually-hidden instead of hidden
  packages/components/src/components/@shared/form-field-msg.tsx
  packages/components/src/components/input-checkbox/common.css
  packages/components/src/components/input-color/style.css
  packages/components/src/components/input-date/style.css
  packages/components/src/components/input-email/style.css
  packages/components/src/components/input-file/style.css
  packages/components/src/components/input-number/style.css
  packages/components/src/components/input-password/style.css
  packages/components/src/components/input-radio/component.tsx
  packages/components/src/components/input-radio/style.css
  packages/components/src/components/input-range/style.css
  packages/components/src/components/input-text/style.css
  packages/components/src/components/input/component.tsx
  packages/components/src/components/link.css
  packages/components/src/components/popover/style.css
  packages/components/src/components/select/style.css
  packages/components/src/components/style.css
  packages/components/src/components/textarea/style.css
  packages/components/src/dev/theme-registration.ts
  packages/samples/react/src/components/input-text/hide-errors.tsx
  packages/samples/react/src/components/input-text/routes.ts
Labels: a11y-retest, v2

#6077 fix: use visually-hidden instead of hidden
  packages/components/package.json
  packages/components/src/components/@shared/form-field-msg.tsx
  packages/components/src/components/input-checkbox/common.css
  packages/components/src/components/input-color/style.css
  packages/components/src/components/input-date/style.css
  packages/components/src/components/input-email/style.css
  packages/components/src/components/input-file/style.css
  packages/components/src/components/input-number/style.css
  packages/components/src/components/input-password/style.css
  packages/components/src/components/input-radio/component.tsx
  packages/components/src/components/input-radio/style.css
  packages/components/src/components/input-range/style.css
  packages/components/src/components/input-text/style.css
  packages/components/src/components/input/component.tsx
  packages/components/src/components/link.css
  packages/components/src/components/popover/style.css
  packages/components/src/components/select/style.css
  packages/components/src/components/style.css
  packages/components/src/components/textarea/style.css
  packages/samples/react/package.json
  packages/samples/react/src/App.tsx
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/src/components/input-text/hide-errors.tsx
  packages/samples/react/src/components/input-text/routes.ts
  packages/samples/react/src/shares/HideMenusContext.ts
Labels: a11y-retest, v1

#6027 Fix tab styling in forced-colors-mode
  packages/samples/react/src/components/tabs/basic.tsx
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tabs-basic-firefox-linux.png
  packages/themes/bmf/src/index.ts
  packages/themes/default/snapshots/theme-default/snapshot-for-tabs-basic-firefox-linux.png
  packages/themes/default/src/components/tabs.scss
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
Labels: a11y-retest, v1

#6055 Fix Error Message Display for Readonly Textarea Fields
  packages/components/src/components/input/component.tsx
Labels: a11y-retest, v1

#6051 Optimize input-text basic
  packages/samples/react/src/components/input-text/partials/cases.tsx
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-text-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-text-basic-firefox-linux.png
Labels: v1

#6044 Resolved inconsistent error handling and message linking across form inputs and radio button.
  packages/samples/react/src/scenarios/appointment-form/AppointmentForm.tsx
  packages/samples/react/src/scenarios/appointment-form/AvailableAppointmentsForm.tsx
  packages/samples/react/src/scenarios/appointment-form/DistrictForm.tsx
  packages/samples/react/src/scenarios/appointment-form/PersonalInformationForm.tsx
Labels: a11y-retest, v1

#6102 refactor: replace `postinstall` with `prepare`
  package.json
  packages/adapters/react-standalone/package.json
  packages/create-kolibri/package.json
  packages/create-kolibri/templates/angular-app/package.json
  packages/create-kolibri/templates/astro-app/package.json
  packages/create-kolibri/templates/kolibri-library/packages/adapters/react/package.json
  packages/create-kolibri/templates/kolibri-library/packages/components/package.json
  packages/create-kolibri/templates/kolibri-library/packages/storybook/package.json
  packages/create-kolibri/templates/next.js-app/package.json
  packages/create-kolibri/templates/preact-app/package.json
  packages/create-kolibri/templates/react-app/package.json
  packages/create-kolibri/templates/solid-app/package.json
  packages/create-kolibri/templates/static-page/package.json
  packages/create-kolibri/templates/stencil-app/package.json
  packages/create-kolibri/templates/vue-app/package.json
  packages/designer/package.json
  packages/samples/react/package.json
  packages/storybook/package.json
  packages/tools/kolibri-cli/.kolibri.config.json
  packages/tools/kolibri-cli/README.md
  packages/tools/kolibri-cli/src/migrate/runner/tasks/v1/assets.ts
Labels: v1

#6103 refactor: replace `postinstall` with `prepare`
  package.json
  packages/adapters/react-standalone/package.json
  packages/create-kolibri/package.json
  packages/create-kolibri/templates/angular-app/package.json
  packages/create-kolibri/templates/astro-app/package.json
  packages/create-kolibri/templates/kolibri-library/packages/adapters/react/package.json
  packages/create-kolibri/templates/kolibri-library/packages/components/package.json
  packages/create-kolibri/templates/kolibri-library/packages/storybook/package.json
  packages/create-kolibri/templates/next.js-app/package.json
  packages/create-kolibri/templates/preact-app/package.json
  packages/create-kolibri/templates/react-app/package.json
  packages/create-kolibri/templates/solid-app/package.json
  packages/create-kolibri/templates/static-page/package.json
  packages/create-kolibri/templates/stencil-app/package.json
  packages/create-kolibri/templates/vue-app/package.json
  packages/designer/.kolibri.config.json
  packages/designer/package.json
  packages/samples/angular/package.json
  packages/samples/library/app/.kolibri.config.json
  packages/samples/library/app/package.json
  packages/samples/library/components/package.json
  packages/samples/library/theme/package.json
  packages/samples/react/.kolibri.config.json
  packages/samples/react/package.json
  packages/samples/ssr/package.json
  packages/storybook/package.json
  packages/tools/kolibri-cli/.kolibri.config.json
  packages/tools/kolibri-cli/README.md
  packages/tools/kolibri-cli/src/migrate/runner/tasks/v1/assets.ts
Labels: v2

#6104 chore: update deps and lock
  package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/adapters/vue/package.json
  packages/components/package.json
  packages/core/package.json
  packages/designer/package.json
  packages/samples/react/package.json
  packages/schema/package.json
  packages/themes/default/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  pnpm-lock.yaml
Labels: v1

#6087 fix: condition to register kolibri once
  packages/components/src/utils/dev.utils.ts
Labels: v1

#6088 fix: condition to register kolibri once
  packages/components/src/components/button/component.tsx
  packages/components/src/components/button/shadow.tsx
  packages/components/src/utils/dev.utils.ts
  packages/components/src/utils/transform-tag-name.ts
Labels: v2

#6097 Fix Error Message Display for Readonly Textarea Fields
  packages/components/src/components/input/component.tsx
Labels: a11y-retest, v2

#6017 Change focus element in scrollable tables in order to fix screen reader output
  packages/components/src/components/table/component.tsx
  packages/components/src/components/table/style.css
  packages/themes/bmf/src/index.ts
  packages/themes/default/src/components/table.scss
  packages/themes/ecl/src/components/ecl-ec/table.scss
  packages/themes/ecl/src/components/ecl-eu/table.scss
  packages/themes/itzbund/src/components/table.scss
Labels: a11y-retest, v1

#6098 Optimize input-text basic
  packages/samples/react/src/components/input-text/partials/cases.tsx
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-text-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-text-basic-firefox-linux.png
Labels: a11y-retest, v2

#6110 fix: value handling for inputs
  packages/components/src/components.d.ts
  packages/components/src/components/input-adapter-leanup/associated.controller.ts
  packages/samples/react/src/scenarios/static-form.tsx
Labels: bug, v2

#6109 fix: value handling for static inputs
  packages/components/src/components/input-adapter-leanup/associated.controller.ts
  packages/samples/react/src/scenarios/static-form.tsx
Labels: bug, v1

#6122 fix: handle form submit and novalidate
  packages/components/src/components/form/controller.ts
  packages/samples/react/src/scenarios/static-form.tsx
  packages/schema/src/utils/a11y.tipps.ts
Labels: bug, v2

#6123 fix: handle form submit and novalidate
  packages/components/src/components/form/controller.ts
  packages/components/src/utils/a11y.tipps.ts
  packages/samples/react/src/scenarios/static-form.tsx
Labels: bug, v1

#6124 Docs/add a disabled scenario
  packages/components/src/components/style.css
  packages/samples/react/src/App.tsx
  packages/samples/react/src/scenarios/disabled-interactive-elements.tsx
  packages/samples/react/src/scenarios/routes.ts
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-accordion-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-button-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-handout-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-date-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-email-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-file-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-number-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-password-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-input-text-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-appointment-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-complex-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-disabled-interactive-scenario-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-select-basic-firefox-linux.png
  packages/themes/bmf/snapshots/theme-bmf/snapshot-for-tabs-icons-only-firefox-linux.png
  packages/themes/bmf/src/index.ts
  packages/themes/default/snapshots/theme-default/snapshot-for-accordion-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-button-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-handout-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-date-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-email-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-file-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-number-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-password-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-text-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-appointment-form-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-complex-form-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-disabled-interactive-scenario-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-static-form-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-select-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-tabs-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-textarea-disabled-firefox-linux.png
  packages/themes/default/src/components/input-checkbox.scss
  packages/themes/default/src/components/input-color.scss
  packages/themes/default/src/components/input-date.scss
  packages/themes/default/src/components/input-email.scss
  packages/themes/default/src/components/input-file.scss
  packages/themes/default/src/components/input-number.scss
  packages/themes/default/src/components/input-password.scss
  packages/themes/default/src/components/input-radio.scss
  packages/themes/default/src/components/input-range.scss
  packages/themes/default/src/components/input-text.scss
  packages/themes/default/src/components/select.scss
  packages/themes/default/src/components/textarea.scss
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: v2

#6095 Fix sidebar prev button on first page
  packages/samples/react/src/App.tsx
  packages/samples/react/src/components/Sidebar.tsx
Labels: v1

#6106 Change focus element in scrollable tables in order to fix screen reader output
  packages/components/src/components/table/component.tsx
  packages/components/src/components/table/style.scss
  packages/themes/bmf/src/index.ts
  packages/themes/default/src/components/table.scss
  packages/themes/ecl/src/components/ecl-ec/table.scss
  packages/themes/ecl/src/components/ecl-eu/table.scss
  packages/themes/itzbund/src/components/table.scss
Labels: v2

#6119 refactor: remove Modal and I18n from Window
  packages/components/src/components/modal/component.tsx
  packages/components/src/core/bootstrap.ts
  packages/components/src/core/config.ts
  packages/components/src/core/i18n.ts
  packages/components/src/global/devtools.ts
  packages/components/src/global/script.ts
  packages/components/src/i18n.ts
  packages/components/src/index.ts
  packages/components/src/utils/dev.utils.ts
  packages/samples/react/src/react.main.tsx
Labels: v2

#6134 refactor(#6019): remove configKoliBri
  packages/components/src/core/bootstrap.ts
  packages/components/src/core/config.ts
Labels: v2

#6082 Improve checkbox visibility with transparent border in forced color mode
  packages/themes/bmf/src/index.ts
  packages/themes/default/src/components/input-checkbox.scss
Labels: a11y-retest, v2
