Repository public-ui/kolibri, pull requests merged in 2025-09, with the labels that each got.

#8360 8255 fix (single-select) onInput has no target
  packages/components/src/components/single-select/shadow.tsx
Labels: v2

#8385 docs: add Toaster migration task and README note
  MIGRATION.de.md
  MIGRATION.md
  docs/BREAKING_CHANGES.v3.md
  packages/tools/kolibri-cli/src/migrate/runner/tasks/v3/index.ts
  packages/tools/kolibri-cli/src/migrate/runner/tasks/v3/toaster.ts
Labels: agent:codex

#8265 feat(table): prevent hiding of fixed columns
  packages/components/playwright.config.ts
  packages/components/src/components/@shared/_kol-table-settings-mixin.scss
  packages/components/src/components/table-stateless/component.tsx
  packages/components/src/components/table-stateless/table-settings-hidable.e2e.ts
  packages/components/src/components/table-stateless/table-settings.e2e.ts
  packages/components/src/components/table-stateless/table-settings.tsx
  packages/components/src/locales/de.ts
  packages/components/src/locales/en.ts
  packages/components/src/schema/types/table-settings.ts
  packages/components/src/schema/types/table.ts
  packages/samples/react/src/components/table/non-hidable-columns.tsx
  packages/samples/react/src/components/table/routes.ts
Labels: agent:codex, finalize:deleonio

#8401 docs(components): explain secondary headline paragraph rendering
  packages/components/src/functional-components/Heading/Heading.tsx
Labels: agent:codex

#8403 docs: note CSS property collision risks
  .github/copilot-instructions.md
  AGENTS.md
  README.md
  docs/HOWTO_KOLIBRI_WEB_COMPONENTS.de.md
  docs/STYLELINT.md
Labels: agent:codex

#8405 fix(a11y): ensure black text on white backgrounds
  packages/components/src/components/a11y.scss
Labels: agent:codex

#8407 fix(components): prevent double unescaping in hashing script
  packages/components/scripts/hashing.js
Labels: agent:codex

#8415 chore(ci): isolate workflow concurrency per pull request
  .github/workflows/benchmark.baseline.yml
  .github/workflows/benchmark.monitoring.yml
  .github/workflows/benchmark.pr-check.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/draft-deploy.yml
  .github/workflows/handle-pr-labels.yml
  .github/workflows/test-deploy.yml
  .github/workflows/update-snapshots.yml
Labels: agent:codex

#8411 fix: update file watching dependency to drop vulnerable braces
  package.json
  pnpm-lock.yaml
Labels: agent:codex

#8410 chore: remove codicon html assets
  packages/components/assets/codicons/codicon.html
  packages/components/src/assets/codicons/codicon.html
Labels: agent:codex

#8416 ci: add ref fallback to concurrency groups
  .github/workflows/benchmark.baseline.yml
  .github/workflows/benchmark.monitoring.yml
  .github/workflows/benchmark.pr-check.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/draft-deploy.yml
  .github/workflows/handle-pr-labels.yml
  .github/workflows/test-deploy.yml
  .github/workflows/update-snapshots.yml
Labels: agent:codex

#8417 fix(components): remove codicon html assets
  packages/components/assets/codicons/codicon.html
  packages/components/src/assets/codicons/codicon.html
Labels: agent:codex

#8420 fix: avoid double unescaping in hashing script
  packages/components/scripts/hashing.js
Labels: agent:codex

#8448 docs: recommend pnpm filter downstream for faster builds
  AGENTS.md
Labels: agent:codex

#8449 docs: add pnpm filter instructions
  AGENTS.md
Labels: agent:codex

#8452 fix(components): include hidden messages in aria-describedby
  AGENTS.md
  packages/components/src/components/combobox/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-checkbox/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-color/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-date/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-email/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-file/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-number/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-password/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-radio/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-range/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input-text/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/select/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/single-select/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/textarea/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/utils/testing/snapshot-input-testing.tsx
Labels: agent:codex

#8454 feat(components): add normalizeMsg utility
  packages/components/src/e2e/input-msg.ts
  packages/components/src/functional-component-wrappers/InputContainerStateWrapper/InputContainerStateWrapper.tsx
  packages/components/src/functional-component-wrappers/_helpers/getRenderStates.ts
  packages/components/src/functional-components/FieldControl/FieldControl.tsx
  packages/components/src/functional-components/FormField/FormField.tsx
  packages/components/src/functional-components/FormFieldMsg/FormFieldMsg.tsx
  packages/components/src/functional-components/InputContainer/InputContainer.tsx
  packages/components/src/functional-components/inputs/Input/Input.tsx
  packages/components/src/functional-components/inputs/NativeSelect/NativeSelect.tsx
  packages/components/src/functional-components/inputs/TextArea/TextArea.tsx
  packages/components/src/schema/props/msg.ts
Labels: agent:codex

#8453 test: fix indentation in remove-msg-props spec
  packages/tools/kolibri-cli/test/remove-msg-props.spec.ts
Labels: agent:codex

#8456 fix: default msg alert props
  packages/components/src/functional-components/FormFieldMsg/FormFieldMsg.tsx
Labels: agent:codex

#8460 chore: enable scheduled dependency update PR
  .github/workflows/auto-dependency-updater.yml
Labels: agent:codex

#8472 fix(samples-react): enable date column sorting
  packages/samples/react/src/components/table/sort-data.tsx
Labels: agent:codex

#8473 fix(table-stateful): warn when sortable column lacks key
  docs/BREAKING_CHANGES.v3.md
  packages/components/src/components/table-stateful/shadow.tsx
  packages/components/src/components/table-stateful/test/validate-headers.spec.ts
Labels: agent:codex

#8524 chore: override axios and semver to remediate CVEs
  package.json
  pnpm-lock.yaml
Labels: agent:codex

#8525 ci: add pnpm audit toggle for security workflow
  .github/workflows/security-scan.yml
Labels: agent:codex

#8504 fix(table-stateless): render td header cell for radio selection
  packages/components/src/components/@shared/_kol-table-stateless-mixin.scss
  packages/components/src/components/table-stateless/component.tsx
  packages/components/src/components/table-stateless/test/__snapshots__/snapshot.spec.tsx.snap
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-table-stateful-with-selection-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-table-stateful-with-single-selection-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-table-stateless-with-selection-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-table-stateless-with-single-selection-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-table-stateful-with-single-selection-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-table-stateless-with-single-selection-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-table-stateful-with-selection-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-table-stateful-with-single-selection-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-table-stateless-with-selection-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-table-stateless-with-single-selection-firefox-linux.png
Labels: agent:codex

#8549 fix(security-scan): scope concurrency per pr
  .github/workflows/security-scan.yml
Labels: agent:codex

#8550 chore: override form-data globally
  package.json
  pnpm-lock.yaml
Labels: agent:codex

#8559 fix(nav): sync collapse aria state with navigation
  packages/components/src/components/nav/shadow.tsx
  packages/components/src/components/nav/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/nav/test/snapshot.spec.tsx
  packages/themes/default/src/components/nav.scss
Labels: agent:codex

#8564 fix: render tooltips only when labels are hidden
  packages/components/src/components/button/component.tsx
  packages/components/src/components/button/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/link/component.tsx
  packages/components/src/components/link/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/functional-components/FieldControl/FieldControl.tsx
  packages/components/src/functional-components/FormField/FormField.tsx
  packages/components/src/functional-components/FormFieldTooltip/FormFieldTooltip.tsx
  packages/components/src/functional-components/FormFieldTooltip/tests/__snapshots__/snapshort.test.tsx.snap
  packages/components/src/functional-components/FormFieldTooltip/tests/snapshort.test.tsx
Labels: agent:codex

#8576 fix: expose aria descriptions directly
  packages/components/src/components/button/component.tsx
  packages/components/src/components/button/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/link/component.tsx
Labels: agent:codex

#8577 fix: align kol-icon aria semantics
  packages/components/src/components/icon/shadow.tsx
  packages/components/src/components/icon/test/icon.mustache
  packages/components/src/components/icon/test/icon.pug
  packages/components/src/components/icon/test/icon.twig
Labels: agent:codex

#8587 fix: improve alert live region announcements
  packages/components/src/components/alert/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/functional-components/Alert/Alert.tsx
  packages/components/src/functional-components/Alert/test/__snapshots__/snapshot.test.tsx.snap
  packages/components/src/functional-components/FormField/tests/__snapshots__/snapshot.test.tsx.snap
  packages/components/src/functional-components/FormFieldMsg/tests/__snapshots__/snapshort.test.tsx.snap
  packages/components/src/functional-components/ToastItem/tests/__snapshots__/snapshot.test.tsx.snap
Labels: agent:codex
