Repository public-ui/kolibri, pull requests merged in 2025-07, with the labels that each got.

#7983 Sample App: Fix sidebar z-index to avoid tooltips overlapping
  packages/samples/react/src/style.scss
Labels: v2

#7998 Transform theme import paths for window support
  packages/samples/react/src/react.main.tsx
  packages/samples/react/vite.config.ts
Labels: v2

#8004 Simplify path transformation
  packages/samples/react/src/react.main.tsx
  packages/samples/react/src/shares/transformUncPathIfNecessary.ts
  packages/tools/visual-tests/tests/axe-snapshots.spec.js
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: v3

#8013 feat(samples-react): remove draft warnings
  packages/samples/react/src/App.tsx
  packages/samples/react/src/components/combobox/basic.tsx
  packages/samples/react/src/components/drawer/basic.tsx
  packages/samples/react/src/components/drawer/controlled.tsx
  packages/samples/react/src/components/popover-button/basic.tsx
  packages/samples/react/src/components/single-select/basic.tsx
  packages/samples/react/src/components/toolbar/basic.tsx
  packages/samples/react/src/components/toolbar/disabled.tsx
  packages/samples/react/src/components/tree/basic.tsx
  packages/samples/react/src/shares/theme.ts
Labels: agent:codex

#8012 Heading: Change HTML-tag for secondary headline to `<p>`
  packages/components/src/components/heading/component.tsx
  packages/components/src/components/heading/style.scss
  packages/components/src/components/heading/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/heading/test/snapshot.spec.tsx
Labels: v2

#8030 remove button row in input scenarios
  packages/samples/react/src/components/FormWrap.tsx
  packages/samples/react/src/components/combobox/basic.tsx
  packages/samples/react/src/components/input-checkbox/basic.tsx
  packages/samples/react/src/components/input-checkbox/button.tsx
  packages/samples/react/src/components/input-checkbox/switch.tsx
  packages/samples/react/src/components/input-color/basic.tsx
  packages/samples/react/src/components/input-date/basic.tsx
  packages/samples/react/src/components/input-email/basic.tsx
  packages/samples/react/src/components/input-file/basic.tsx
  packages/samples/react/src/components/input-number/basic.tsx
  packages/samples/react/src/components/input-password/basic.tsx
  packages/samples/react/src/components/input-radio/basic.tsx
  packages/samples/react/src/components/input-range/basic.tsx
  packages/samples/react/src/components/input-text/basic.tsx
  packages/samples/react/src/components/select/basic.tsx
  packages/samples/react/src/components/single-select/basic.tsx
  packages/samples/react/src/components/textarea/basic.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-combobox-basic-noColumns-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-button-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-checkbox-switch-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-color-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-date-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-email-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-file-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-number-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-password-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-radio-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-range-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-text-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-select-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-single-select-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-textarea-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-combobox-basic-noColumns-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-button-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-checkbox-switch-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-color-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-date-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-email-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-file-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-number-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-password-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-radio-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-range-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-text-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-select-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-single-select-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-textarea-basic-noColumns-firefox-linux.png
Labels: agent:codex

#7969 Implement onClose callback for Toast
  packages/components/src/components/toaster/shadow.tsx
  packages/components/src/schema/components/toaster.ts
  packages/samples/react/src/components/toast/basic.tsx
  packages/samples/react/vite.config.ts
Labels: v2

#8033 refactor: enforce explicit boolean comparisons
  packages/components/src/components/button/component.tsx
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/single-select/shadow.tsx
Labels: agent:codex

#8042 Disable accessible autocomplete overlay comments
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/combobox/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/form/shadow.tsx
  packages/components/src/components/single-select/shadow.tsx
  packages/components/src/components/single-select/test/__snapshots__/snapshot.spec.tsx.snap
Labels: agent:codex

#8052 Add important CLI version note
  packages/tools/kolibri-cli/README.md
Labels: agent:codex

#8047 Add mocha tests to cli package
  packages/tools/kolibri-cli/.gitignore
  packages/tools/kolibri-cli/package.json
  packages/tools/kolibri-cli/test/cli-interface.spec.ts
  packages/tools/kolibri-cli/test/end-to-end-migration.spec.ts
  packages/tools/kolibri-cli/test/exec-task.spec.ts
  packages/tools/kolibri-cli/test/generic-rename-slot.spec.ts
  packages/tools/kolibri-cli/test/generic-rename-tag.spec.ts
  packages/tools/kolibri-cli/test/gitignore-add-rule.spec.ts
  packages/tools/kolibri-cli/test/handle-dependency.spec.ts
  packages/tools/kolibri-cli/test/json-task.spec.ts
  packages/tools/kolibri-cli/test/label-expert-slot.spec.ts
  packages/tools/kolibri-cli/test/mark-removed-slot.spec.ts
  packages/tools/kolibri-cli/test/merge-html.spec.ts
  packages/tools/kolibri-cli/test/npmrc-add-rule.spec.ts
  packages/tools/kolibri-cli/test/refactor-property-error.spec.ts
  packages/tools/kolibri-cli/test/refactor-property-icon-align.spec.ts
  packages/tools/kolibri-cli/test/refactor-property-label.spec.ts
  packages/tools/kolibri-cli/test/remove-property.spec.ts
  packages/tools/kolibri-cli/test/remove-task.spec.ts
  packages/tools/kolibri-cli/test/rename-property.spec.ts
  packages/tools/kolibri-cli/test/rename-slot.spec.ts
  packages/tools/kolibri-cli/test/rename-tag.spec.ts
  packages/tools/kolibri-cli/test/task-runner.spec.ts
  packages/tools/kolibri-cli/test/tsconfig-reconfigure.spec.ts
  packages/tools/kolibri-cli/test/update-property-value.spec.ts
  packages/tools/kolibri-cli/test/vscode-settings-reconfigure.spec.ts
  packages/tools/kolibri-cli/tsconfig.test.json
Labels: agent:codex

#8058 fix(cli): resolve build failure
  packages/tools/kolibri-cli/src/migrate/shares/reuse.ts
  packages/tools/visual-tests/src/index.js
Labels: codex

#8059 Improve CLI tag detection
  packages/tools/kolibri-cli/src/migrate/index.ts
  packages/tools/kolibri-cli/src/migrate/shares/reuse.ts
Labels: codex

#8090 Fix CLI test timeouts
  packages/tools/kolibri-cli/src/index.ts
  packages/tools/kolibri-cli/test/cli-interface.spec.ts
Labels: codex

#8037 Add helpful warnings to migration tool
  packages/tools/kolibri-cli/package.json
  packages/tools/kolibri-cli/src/index.ts
  packages/tools/kolibri-cli/src/info/index.ts
  packages/tools/kolibri-cli/src/migrate/index.ts
  packages/tools/kolibri-cli/src/migrate/shares/reuse.ts
  packages/tools/kolibri-cli/src/types.ts
  packages/tools/kolibri-cli/test/cli-interface.spec.ts
  packages/tools/visual-tests/src/index.js
Labels: agent:codex

#8091 feat(components): unify mode variable
  packages/components/src/i18n.ts
  packages/components/src/schema/utils/prop.validators.ts
  packages/components/src/schema/utils/reuse.ts
  packages/components/src/utils/align-floating-elements.ts
  packages/components/src/utils/dev.utils.ts
Labels: codex

#8084 Refactor translations to use cached values
  AGENTS.md
  packages/components/src/components/card/component.tsx
  packages/components/src/components/form/shadow.tsx
  packages/components/src/components/input-file/shadow.tsx
  packages/components/src/components/input-password/shadow.tsx
  packages/components/src/components/kolibri/shadow.tsx
  packages/components/src/components/link/component.tsx
  packages/components/src/components/modal/shadow.tsx
  packages/components/src/components/pagination/component.tsx
  packages/components/src/components/single-select/shadow.tsx
  packages/components/src/components/spin/shadow.tsx
  packages/components/src/components/table-stateless/component.tsx
  packages/components/src/components/table-stateless/table-settings.tsx
  packages/components/src/components/toaster/shadow.tsx
  packages/components/src/components/version/shadow.tsx
  packages/components/src/functional-components/Alert/Alert.tsx
  packages/components/src/functional-components/AlertIcon/AlertIcon.tsx
  packages/components/src/functional-components/CustomSuggestionsToggle/CustomSuggestionsToggle.tsx
  packages/components/src/functional-components/FormFieldCounter/FormFieldCounter.tsx
Labels: codex

#8096 Deactivate benchmark workflows
  .github/workflows/benchmark.monitoring.yml
  .github/workflows/benchmark.pr-check.yml
Labels: codex

#8097 Add property naming guideline
  packages/components/AGENTS.md
Labels: codex

#8100 Handle PR-Labels
  .github/workflows/handle-pr-labels.yml
Labels: agent:codex, codex

#7707 Implement character limit feature for inputs
  packages/components/src/components/@deprecated/input/controller.ts
  packages/components/src/components/input-email/controller.ts
  packages/components/src/components/input-email/input-email.e2e.ts
  packages/components/src/components/input-email/shadow.tsx
  packages/components/src/components/input-password/controller.ts
  packages/components/src/components/input-password/input-password.e2e.ts
  packages/components/src/components/input-password/shadow.tsx
  packages/components/src/components/input-text/input-text.e2e.ts
  packages/components/src/components/input-text/shadow.tsx
  packages/components/src/components/input/types.ts
  packages/components/src/components/textarea/controller.ts
  packages/components/src/components/textarea/shadow.tsx
  packages/components/src/components/textarea/textarea.e2e.ts
  packages/components/src/e2e/index.ts
  packages/components/src/e2e/input-character-limit.ts
  packages/components/src/e2e/inputs-common.e2e.ts
  packages/components/src/functional-component-wrappers/FormFieldStateWrapper/FormFieldStateWrapper.tsx
  packages/components/src/functional-component-wrappers/InputStateWrapper/InputStateWrapper.tsx
  packages/components/src/functional-component-wrappers/TextAreaStateWrapper/TextAreaStateWrapper.tsx
  packages/components/src/functional-components/FormField/FormField.tsx
  packages/components/src/functional-components/FormField/tests/__snapshots__/snapshot.test.tsx.snap
  packages/components/src/functional-components/FormField/tests/snapshot.test.tsx
  packages/components/src/functional-components/FormFieldCharacterLimitHint/FormFieldCharacterLimitHint.tsx
  packages/components/src/functional-components/FormFieldCounter/FormFieldCounter.tsx
  packages/components/src/functional-components/FormFieldCounter/tests/__snapshots__/snapshot.test.tsx.snap
  packages/components/src/functional-components/FormFieldCounter/tests/snapshot.test.tsx
  packages/components/src/locales/de.ts
  packages/components/src/locales/en.ts
  packages/components/src/schema/components/index.ts
  packages/components/src/schema/components/input-email.ts
  packages/components/src/schema/components/input-password.ts
  packages/components/src/schema/components/input-text.ts
  packages/components/src/schema/components/input.ts
  packages/components/src/schema/components/textarea.ts
  packages/components/src/schema/props/index.ts
  packages/components/src/schema/props/max-length-behavior.ts
  packages/samples/react/src/components/input-text/partials/cases.tsx
  packages/samples/react/src/components/textarea/counter.tsx
  packages/samples/react/src/components/textarea/routes.ts
  packages/samples/react/src/components/textarea/with-counter.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-input-text-basic-noColumns-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-textarea-with-counter-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-input-text-basic-noColumns-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-textarea-with-counter-firefox-linux.png
  packages/themes/default/src/mixins/form-field.scss
  packages/themes/ecl/src/ecl-ec/mixins/form-field.scss
  packages/themes/ecl/src/ecl-eu/mixins/form-field.scss
Labels: a11y

#8103 Add AGENTS instructions for themes
  packages/themes/AGENTS.md
Labels: agent:codex

#8104 Explain typed-bem workflow
  packages/components/AGENTS.md
Labels: agent:codex

#8125 Fix input counter not updating when value is set to empty string
  packages/components/src/components/input-password/controller.ts
  packages/components/src/components/textarea/controller.ts
Labels: v2

#8110 refactor: use the correct prop types
  packages/components/src/components/@deprecated/input/controller.ts
  packages/components/src/components/button/component.tsx
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/input-checkbox/shadow.tsx
  packages/components/src/components/input-color/shadow.tsx
  packages/components/src/components/input-date/shadow.tsx
  packages/components/src/components/input-email/shadow.tsx
  packages/components/src/components/input-file/shadow.tsx
  packages/components/src/components/input-number/shadow.tsx
  packages/components/src/components/input-password/controller.ts
  packages/components/src/components/input-password/shadow.tsx
  packages/components/src/components/input-radio/shadow.tsx
  packages/components/src/components/input-range/shadow.tsx
  packages/components/src/components/input-text/shadow.tsx
  packages/components/src/components/link/component.tsx
  packages/components/src/components/select/shadow.tsx
  packages/components/src/components/single-select/shadow.tsx
  packages/components/src/components/textarea/controller.ts
  packages/components/src/components/textarea/shadow.tsx
  packages/components/src/schema/components/combobox.ts
  packages/components/src/schema/components/input-checkbox.ts
  packages/components/src/schema/components/input-color.ts
  packages/components/src/schema/components/input-date.ts
  packages/components/src/schema/components/input-email.ts
  packages/components/src/schema/components/input-file.ts
  packages/components/src/schema/components/input-number.ts
  packages/components/src/schema/components/input-password.ts
  packages/components/src/schema/components/input-radio.ts
  packages/components/src/schema/components/input-range.ts
  packages/components/src/schema/components/input-text.ts
  packages/components/src/schema/components/select.ts
  packages/components/src/schema/components/single-select.ts
  packages/components/src/schema/components/textarea.ts
  packages/components/src/schema/props/aria-selected.ts
  packages/components/src/schema/props/hint.ts
  packages/components/src/schema/props/index.ts
Labels: agent:codex

#8151 feat(spin): simplify label
  packages/components/src/components/spin/shadow.tsx
  packages/components/src/components/spin/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/spin/test/snapshot.spec.tsx
  packages/components/src/schema/components/spin.ts
  packages/samples/react/src/components/spin/label.tsx
  packages/samples/react/src/components/spin/routes.ts
Labels: agent:codex

#8157 test: Add reset e2e test for InputFile
  packages/components/src/components/input-file/input-file.e2e.ts
Labels: agent:codex

#8158 Fix sample link list style
  packages/samples/react/src/style.scss
Labels: agent:codex

#8159 Fix list bullets in SampleDescription
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/unocss.config.ts
Labels: agent:codex

#8165 Add unit prop schema
  packages/components/src/components/progress/shadow.tsx
  packages/components/src/schema/props/index.ts
  packages/components/src/schema/props/unit.ts
Labels: agent:codex

#8171 Add allow multi sort prop
  packages/components/src/components/table-stateful/shadow.tsx
  packages/components/src/schema/props/allow-multi-sort.ts
  packages/components/src/schema/props/index.ts
Labels: agent:codex
