Repository public-ui/kolibri, pull requests merged in 2025-05, with the labels that each got.

#7622 Refactor SampleDescription component and update documentation links
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/src/react.main.tsx
  packages/samples/react/src/shares/constants.ts
  packages/samples/react/src/style.scss
Labels: v2

#7623 fix: refactor SampleDescription component and update documentation links
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/src/style.scss
Labels: v3

#7629 fix: update grid classes for responsive design
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/src/components/handout/basic.tsx
Labels: v3

#7628 fix: update grid classes for responsive design
  packages/samples/react/src/components/SampleDescription.tsx
  packages/samples/react/src/components/handout/basic.tsx
Labels: v2

#7631 fix: update layout classes for better responsiveness
  packages/samples/react/src/scenarios/change-tabindex.tsx
Labels: v3

#7630 fix: update layout classes for better responsiveness
  packages/samples/react/src/scenarios/change-tabindex.tsx
Labels: v2

#7633 fix: update layout classes for better responsiveness
  packages/samples/react/src/components/badge/basic.tsx
  packages/samples/react/src/components/badge/button.tsx
  packages/samples/react/src/components/button/baselined.tsx
  packages/samples/react/src/components/link-button/aria-description.tsx
  packages/samples/react/src/components/link-button/basic.tsx
  packages/samples/react/src/components/tree/basic.tsx
  packages/samples/react/src/style.scss
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-badge-basic-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-badge-button-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-button-baselined-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-button-baselined-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-link-button-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-link-button-basic-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-tree-basic-home-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-tree-basic-home-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-badge-basic-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-badge-button-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-button-baselined-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-button-baselined-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-link-button-basic-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-link-button-basic-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-tree-basic-home-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-tree-basic-home-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-badge-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-badge-button-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-button-baselined-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-button-baselined-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-link-button-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-link-button-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-tree-basic-home-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-tree-basic-home-zoom-firefox-linux.png
Labels: v2

#7644 fix: remove ts-prune references from package.json and related files
  package.json
  packages/.ts-prunerc.js
  packages/components/src/components/@else/all/component.tsx
  packages/components/src/components/@else/counter/component.tsx
  packages/components/src/schema/utils/contrast/contrast.ts
  packages/designer/.ts-prunerc.js
  packages/designer/package.json
  packages/samples/react/.knip.json
  packages/samples/react/.ts-prunerc.js
  packages/samples/react/package.json
  packages/samples/react/src/shares/store.ts
  packages/samples/react/unocss.config.ts
  pnpm-lock.yaml
Labels: v2

#7643 fix: remove ts-prune references from package.json and related files
  package.json
  packages/.ts-prunerc.js
  packages/components/src/components/@else/all/component.tsx
  packages/components/src/components/@else/counter/component.tsx
  packages/components/src/schema/utils/contrast/contrast.ts
  packages/samples/react/unocss.config.ts
  pnpm-lock.yaml
Labels: v3

#7641 SingleSelect: Fix prop/state synchronization
  packages/components/src/components/single-select/shadow.tsx
Labels: v2

#7619 Fix (input-file) unify cursor styling and prevent focus when disabled
  packages/components/src/components/input-file/style.scss
Labels: v3

#7587 feat: add stylelint configuration and update package.json for SCSS linting
  .vscode/settings.json
  package.json
  packages/components/.stylelintignore
  packages/components/.stylelintrc.json
  packages/components/package.json
  packages/samples/react/.stylelintrc.json
  packages/samples/react/package.json
  packages/themes/default/.stylelintrc.json
  packages/themes/default/package.json
  packages/themes/ecl/.stylelintrc.json
  packages/themes/ecl/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v3

#7640 Fix focus on link button in toolbar
  packages/components/src/components/toolbar/shadow.tsx
  packages/components/src/components/toolbar/style.scss
  packages/components/src/components/toolbar/test/__snapshots__/snapshot.spec.tsx.snap
Labels: v2

#7639 Fix focus on link button in toolbar
  packages/components/src/components/toolbar/shadow.tsx
  packages/components/src/components/toolbar/style.scss
  packages/components/src/components/toolbar/test/__snapshots__/snapshot.spec.tsx.snap
Labels: v3

#7648 Fix navigation style: Always left align labels
  packages/components/src/components/nav/style.scss
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-nav-basic-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-nav-horizontal-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-nav-basic-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-nav-horizontal-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-horizontal-zoom-firefox-linux.png
Labels: v2

#7544 feat: add stylelint configuration and update package.json for SCSS linting
  .vscode/settings.json
  package.json
  packages/components/.stylelintignore
  packages/components/.stylelintrc.json
  packages/components/package.json
  packages/components/src/components/input-date/input-date.e2e.ts
  packages/components/src/components/progress/test/snapshot.spec.tsx
  packages/samples/react/.stylelintrc.json
  packages/samples/react/package.json
  packages/themes/bwst/.stylelintrc.json
  packages/themes/bwst/package.json
  packages/themes/default/.stylelintrc.json
  packages/themes/default/package.json
  packages/themes/ecl/.stylelintrc.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/.stylelintrc.json
  packages/themes/itzbund/package.json
  packages/themes/package.json
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  pnpm-lock.yaml
Labels: v2

#7650 feat: integrate @public-ui/theme-ecl into the project
  .github/workflows/publish.yml
  packages/samples/react/.knip.json
  packages/samples/react/package.json
  packages/samples/react/src/react.main.tsx
  packages/samples/react/webpack.config.js
  packages/themes/ecl/README.md
  packages/themes/ecl/package.json
  pnpm-lock.yaml
  scripts/deprecate-add.sh
  scripts/deprecate-rm.sh
  scripts/dist-tags.sh
  scripts/license-reports.sh
Labels: v3

#7636 Fix drawer content not expanding properly
  packages/components/src/components/drawer/style.scss
  packages/samples/react/src/components/drawer/basic.tsx
  packages/samples/react/src/style.scss
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-drawer-basic-align-left-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-drawer-basic-align-left-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-drawer-basic-align-right-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-drawer-basic-align-right-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-drawer-basic-align-left-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-drawer-basic-align-left-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-drawer-basic-align-right-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-drawer-basic-align-right-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-drawer-basic-align-left-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-drawer-basic-align-left-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-drawer-basic-align-right-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-drawer-basic-align-right-zoom-firefox-linux.png
Labels: v2

#7638 Fix drawer content not expanding properly
  packages/components/src/components/drawer/style.scss
  packages/samples/react/src/components/drawer/basic.tsx
  packages/samples/react/src/style.scss
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-drawer-basic-align-left-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-drawer-basic-align-left-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-drawer-basic-align-right-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-drawer-basic-align-right-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-drawer-basic-align-left-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-drawer-basic-align-left-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-drawer-basic-align-right-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-drawer-basic-align-right-zoom-firefox-linux.png
Labels: v3

#7672 Update Netlify configuration
  .github/workflows/dod-checker.yml
  .github/workflows/draft-deploy.yml
  .github/workflows/test-deploy.yml
  netlify.toml
Labels: v1

#7670 Update Netlify configuration
  .github/workflows/draft-deploy.yml
  .github/workflows/test-deploy.yml
  netlify.toml
Labels: v3

#7671 Update Netlify configuration
  .github/workflows/draft-deploy.yml
  .github/workflows/test-deploy.yml
  netlify.toml
Labels: v2

#7667 Fix navigation style: Always left align labels
  packages/components/src/components/nav/style.scss
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-nav-basic-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-nav-horizontal-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-horizontal-zoom-firefox-linux.png
Labels: v3

#7676 Enhance DoD workflow to include 'ready_for_review' event
  .github/workflows/dod-checker.yml
Labels: v2

#7678 Enhance DoD workflow to include 'ready_for_review' trigger
  .github/dod.yml
  .github/workflows/dod-checker.yml
Labels: v1

#7677 Enhance DoD workflow to include 'ready_for_review' trigger
  .github/workflows/dod-checker.yml
Labels: v3

#7674 refact: Refactor snapshot tests to conditionally skip based on options
  packages/tools/visual-tests/tests/sample-app.routes.js
  packages/tools/visual-tests/tests/theme-snapshots.spec.js
Labels: v2

#7673 refact: Add accessibility snapshot tests using Playwright and Axe
  packages/tools/visual-tests/tests/axe-snapshots.spec.js
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: v2

#7680 #7669 - Anpassung der Button-Hierarchie im Default-Theme
  packages/samples/react/src/components/button/partials/cases.tsx
  packages/themes/default/README.md
  packages/themes/default/src/global.scss
  packages/themes/default/src/mixins/button.scss
Labels: v2

#7682 refactor: remove variant css class on button-wc host
  packages/components/src/components/button/shadow.tsx
  packages/components/src/components/button/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/link-button/shadow.tsx
  packages/components/src/components/link-button/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/link/component.tsx
  packages/components/src/components/link/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/popover-button/shadow.tsx
  packages/components/src/components/popover-button/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/split-button/shadow.tsx
  packages/components/src/components/split-button/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/schema/components/link.ts
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-link-button-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-link-button-basic-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-disabled-interactive-scenario-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-disabled-interactive-scenario-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-linkButton-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-linkButton-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-same-height-of-all-interactive-elements-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-same-height-of-all-interactive-elements-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-scenarios-focus-elements-component-linkButton-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-scenarios-focus-elements-component-linkButton-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-split-button-basic-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-split-button-basic-zoom-firefox-linux.png
  packages/themes/bwst/src/components/button.scss
  packages/themes/bwst/src/components/link-button.scss
  packages/themes/bwst/src/components/split-button.scss
  packages/themes/bwst/src/components/toolbar.scss
  packages/themes/bwst/src/mixins/button.scss
  packages/themes/bwst/src/mixins/rem.scss
  packages/themes/default/snapshots/theme-default/snapshot-for-link-button-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-link-button-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-disabled-interactive-scenario-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-disabled-interactive-scenario-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-linkButton-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-linkButton-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-same-height-of-all-interactive-elements-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-same-height-of-all-interactive-elements-zoom-firefox-linux.png
  packages/themes/default/src/components/link-button.scss
  packages/themes/default/src/components/split-button.scss
  packages/themes/default/src/components/toolbar.scss
  packages/themes/default/src/mixins/button.scss
  packages/themes/ecl/src/ecl-ec/components/button.scss
  packages/themes/ecl/src/ecl-ec/components/link-button.scss
  packages/themes/ecl/src/ecl-ec/components/toolbar.scss
  packages/themes/ecl/src/ecl-ec/mixins/button.scss
  packages/themes/ecl/src/ecl-eu/components/link-button.scss
  packages/themes/ecl/src/ecl-eu/components/split-button.scss
  packages/themes/ecl/src/ecl-eu/mixins/button.scss
  packages/themes/itzbund/src/components/button.scss
  packages/themes/itzbund/src/components/link-button.scss
  packages/themes/itzbund/src/components/split-button.scss
  packages/themes/itzbund/src/mixins/button.scss
Labels: v2

#7662 Fix dropdown closing behavior on selection in combobox and single-select
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/single-select/shadow.tsx
  packages/themes/bwst/src/components/combobox.scss
  packages/themes/bwst/src/components/single-select.scss
  packages/themes/default/src/components/combobox.scss
  packages/themes/default/src/components/single-select.scss
  packages/themes/ecl/src/ecl-ec/components/combobox.scss
  packages/themes/ecl/src/ecl-ec/components/single-select.scss
  packages/themes/ecl/src/ecl-eu/components/combobox.scss
  packages/themes/ecl/src/ecl-eu/components/single-select.scss
  packages/themes/itzbund/src/components/combobox.scss
  packages/themes/itzbund/src/components/single-select.scss
Labels: v2

#7694 fix: normal button styled
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-link-button-basic-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-linkButton-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-link-button-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-focus-elements-component-linkButton-firefox-linux.png
  packages/themes/default/src/mixins/button.scss
Labels: v3

#7726 fix(nav): adjust padding for vertical list and remove margin from exp…
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-nav-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-nav-horizontal-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-nav-horizontal-firefox-linux.png
  packages/themes/default/src/components/nav.scss
Labels: v3
