Repository public-ui/kolibri, pull requests merged in 2025-03, with the labels that each got.

#7428 Improve _value type for single select: Allow arbitrary values
  packages/components/src/components/single-select/controller.ts
  packages/components/src/components/single-select/shadow.tsx
  packages/components/src/schema/components/single-select.ts
Labels: v3

#7429 Improve _value type for single select: Allow arbitrary values
  packages/components/src/components/single-select/controller.ts
  packages/components/src/components/single-select/readme.md
  packages/components/src/components/single-select/shadow.tsx
  packages/components/src/schema/components/single-select.ts
Labels: v2

#7440 fix: value length at progress bar when unit is percentage
  packages/components/src/components/progress/shadow.tsx
  packages/components/src/components/progress/test/__snapshots__/snapshot.spec.tsx.snap
  packages/samples/react/src/components/progress/basic.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-handout-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-handout-basic-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-progress-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-progress-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-handout-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-handout-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-progress-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-progress-basic-zoom-firefox-linux.png
Labels: v3

#7439 fix: value length at progress bar when unit is percentage
  packages/components/src/components/progress/shadow.tsx
  packages/components/src/components/progress/test/__snapshots__/snapshot.spec.tsx.snap
  packages/samples/react/src/components/progress/basic.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-handout-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-handout-basic-zoom-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-progress-basic-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-progress-basic-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-handout-basic-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-handout-basic-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-progress-basic-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-progress-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-handout-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-handout-basic-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-progress-basic-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-progress-basic-zoom-firefox-linux.png
Labels: v2

#7444 chore: update npm-run-all to version 7.0.2
  package.json
  packages/designer/package.json
  packages/samples/react/package.json
  pnpm-lock.yaml
Labels: v2

#7457 Configure CLA assistant to use App token instead of personal token
  .github/workflows/cla.yml
Labels: v3

#7459 Configure CLA assistant to use App token instead of personal token
  .github/workflows/cla.yml
Labels: v1

#7461 refactor: extract default snapshot options for visual tests
  .github/actions/pnpm-setup/action.yml
  .github/workflows/auto-dependency-updater.yml
  .github/workflows/draft-deploy.yml
  .github/workflows/publish.yml
  .github/workflows/test-deploy.yml
  .github/workflows/update-snapshots.yml
  packages/tools/visual-tests/tests/axe-snapshots.spec.js.bak
  packages/tools/visual-tests/tests/theme-snapshots.spec.js
Labels: v2

#7462 refactor: extract default snapshot options for visual tests
  .github/actions/pnpm-setup/action.yml
  .github/workflows/auto-dependency-updater.yml
  .github/workflows/draft-deploy.yml
  .github/workflows/publish.yml
  .github/workflows/test-deploy.yml
  .github/workflows/update-snapshots.yml
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-table-sort-data-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-table-sort-data-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-table-sort-data-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-table-sort-data-zoom-firefox-linux.png
  packages/tools/visual-tests/tests/axe-snapshots.spec.js.bak
  packages/tools/visual-tests/tests/theme-snapshots.spec.js
Labels: v3

#7468 Optimize message rendering
  packages/components/src/components/component-list.ts
  packages/components/src/components/input/component.tsx
  packages/components/src/components/input/controller.ts
  packages/components/src/components/input/test/__snapshots__/snapshot.spec.tsx.snap
  packages/components/src/components/input/test/snapshot.spec.tsx
  packages/components/src/functional-components/FieldControl/FieldControl.tsx
  packages/components/src/functional-components/FormField/FormField.tsx
  packages/components/src/functional-components/InputContainer/InputContainer.tsx
  packages/components/src/functional-components/inputs/Checkbox/Checkbox.tsx
  packages/components/src/functional-components/inputs/Input/Input.tsx
  packages/components/src/functional-components/inputs/NativeSelect/NativeSelect.tsx
  packages/components/src/functional-components/inputs/TextArea/TextArea.tsx
  packages/components/src/schema/props/msg.ts
Labels: v3

#7494 Fix KolInputRadio value matching by removing mapString2Unknown functionality
  packages/components/src/components/input-radio/controller.ts
  packages/components/src/components/input-radio/input-radio.e2e.ts
  packages/components/src/schema/utils/prop.validators.ts
Labels: v3

#7503 Fix pnpm version and fix package path to sample app
  package.json
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/tools/visual-tests/package.json
  packages/tools/visual-tests/src/index.js
Labels: v3

#7502 Fix pnpm version and fix package path to sample app
  package.json
  packages/themes/bwst/package.json
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/itzbund/package.json
  packages/tools/visual-tests/package.json
  packages/tools/visual-tests/src/index.js
Labels: v2

#7507 chore: serve default theme on windows
  packages/themes/default/package.json
  packages/themes/default/serve.sh
Labels: v2

#7508 chore: fix serve default theme on windows
  packages/themes/default/package.json
  packages/themes/default/serve.sh
Labels: v3

#7471 chore: update dependencies across multiple packages to latest versions
  package.json
  packages/adapters/angular/v15/package.json
  packages/adapters/angular/v16/package.json
  packages/adapters/angular/v17/package.json
  packages/adapters/angular/v18/package.json
  packages/adapters/preact/package.json
  packages/adapters/react-standalone/package.json
  packages/adapters/react/package.json
  packages/adapters/solid/package.json
  packages/adapters/vue/package.json
  packages/components/package.json
  packages/components/src/styles/_kol-custom-suggestions-options-group.scss
  packages/components/src/styles/_kol-form-field-mixin.scss
  packages/components/src/styles/_kol-input-mixin.scss
  packages/samples/angular/package.json
  packages/samples/react/package.json
  packages/samples/react/src/components/input-date/partials/cases.tsx
  packages/samples/react/src/components/link/short-key.tsx
  packages/samples/react/src/scenarios/change-tabindex.tsx
  packages/themes/default/package.json
  packages/themes/ecl/package.json
  packages/themes/ecl/src/ecl-ec/components/combobox.scss
  packages/themes/ecl/src/ecl-ec/components/single-select.scss
  packages/themes/ecl/src/ecl-ec/components/split-button.scss
  packages/themes/ecl/src/ecl-ec/components/tabs.scss
  packages/themes/ecl/src/ecl-ec/mixins/button.scss
  packages/themes/ecl/src/ecl-ec/mixins/input-container.scss
  packages/themes/ecl/src/ecl-ec/mixins/input-text.scss
  packages/themes/ecl/src/ecl-eu/components/combobox.scss
  packages/themes/ecl/src/ecl-eu/components/single-select.scss
  packages/themes/ecl/src/ecl-eu/components/tabs.scss
  packages/themes/ecl/src/ecl-eu/mixins/button.scss
  packages/themes/ecl/src/ecl-eu/mixins/input-container.scss
  packages/themes/ecl/src/ecl-eu/mixins/input-text.scss
  packages/tools/kolibri-cli/package.json
  packages/tools/visual-tests/package.json
  packages/tools/visual-tests/playwright.config.js
  packages/tools/visual-tests/tests/theme-snapshots.spec.js
  pnpm-lock.yaml
Labels: v3

#7512 fix: input `icons` and select `options` props
  packages/components/src/components/@deprecated/input/controller-icon.ts
  packages/components/src/components/@deprecated/input/types-icon.ts
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/input-color/shadow.tsx
  packages/components/src/components/input-date/shadow.tsx
  packages/components/src/components/input-email/shadow.tsx
  packages/components/src/components/input-file/shadow.tsx
  packages/components/src/components/input-number/shadow.tsx
  packages/components/src/components/input-password/shadow.tsx
  packages/components/src/components/input-range/shadow.tsx
  packages/components/src/components/input-text/shadow.tsx
  packages/components/src/components/input/component.tsx
  packages/components/src/components/input/types.ts
  packages/components/src/components/select/shadow.tsx
  packages/components/src/components/single-select/shadow.tsx
  packages/components/src/components/textarea/shadow.tsx
  packages/components/src/schema/components/combobox.ts
  packages/components/src/schema/components/input-color.ts
  packages/components/src/schema/components/input-date.ts
  packages/components/src/schema/components/input-email.ts
  packages/components/src/schema/components/input-file.ts
  packages/components/src/schema/components/input-number.ts
  packages/components/src/schema/components/input-password.ts
  packages/components/src/schema/components/input-range.ts
  packages/components/src/schema/components/input-text.ts
  packages/components/src/schema/components/input.ts
  packages/components/src/schema/components/select.ts
  packages/components/src/schema/components/single-select.ts
  packages/components/src/schema/components/textarea.ts
  packages/components/src/schema/props/icons.ts
  packages/components/src/schema/types/icons.ts
  packages/components/src/schema/types/input/control/number.ts
  packages/samples/react/src/scenarios/routes.ts
  packages/samples/react/src/scenarios/same-height-of-all-interactive-elements.tsx
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-same-height-of-all-interactive-elements-firefox-linux.png
  packages/test-tag-name-transformer/snapshots/theme-default/snapshot-for-scenarios-same-height-of-all-interactive-elements-zoom-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-scenarios-same-height-of-all-interactive-elements-firefox-linux.png
  packages/themes/bwst/snapshots/theme-bwst/snapshot-for-scenarios-same-height-of-all-interactive-elements-zoom-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-same-height-of-all-interactive-elements-firefox-linux.png
  packages/themes/default/snapshots/theme-default/snapshot-for-scenarios-same-height-of-all-interactive-elements-zoom-firefox-linux.png
  packages/tools/visual-tests/tests/sample-app.routes.js
Labels: v2
