Repository public-ui/kolibri, pull requests merged in 2025-06, with the labels that each got.

#7816 docs: remove draft warning from combobox
  packages/components/src/components/combobox/readme.md
Labels: v2

#7814 docs: removed outdated warning and enhanced tree component documentation
  packages/components/src/components/tree/readme.md
Labels: v2

#7896 Add package AGENTS
  AGENTS.md
  packages/components/AGENTS.md
  packages/samples/react/AGENTS.md
Labels: codex

#7908 Remove angular v15/v16 references
  .github/workflows/publish.yml
  lerna.json
Labels: codex

#7910 Reconfigure prettier to check also the config files
  .github/DISCUSSION_TEMPLATE/ideas.yml
  .github/DISCUSSION_TEMPLATE/q-a.yml
  .github/ISSUE_TEMPLATE/3.doc_report.yml
  README.md
  docs/BREAKING_CHANGES.v2.md
  docs/tutorials/NEW_COMPONENT.md
  docs/tutorials/new-component/test/html.mock.ts
  package.json
  packages/components/.lintstagedrc
  packages/components/prettier.config.js
  packages/components/scripts/hashing.js
  packages/samples/react/.lintstagedrc
  packages/samples/react/unocss.config.ts
  packages/themes/.lintstagedrc
  packages/themes/default/.lintstagedrc
  packages/themes/default/tsconfig.json
  packages/themes/ecl/.lintstagedrc
  packages/themes/ecl/tsconfig.json
  packages/tools/benchmark-tests/benchmark-baseline.json
  packages/tools/kolibri-cli/.kolibri.config.json
  packages/tools/kolibri-cli/.lintstagedrc
  pnpm-lock.yaml
Labels: agent:warp

#7928 Activate eqeqeq eslint rule
  packages/components/.eslintrc.js
  packages/components/src/components/combobox/shadow.tsx
  packages/components/src/components/input-date/controller.ts
  packages/components/src/components/nav/shadow.tsx
  packages/components/src/components/progress/shadow.tsx
  packages/components/src/components/table-stateful/shadow.tsx
  packages/samples/react/.eslintrc.js
  packages/samples/react/src/components/drawer/basic.tsx
  packages/themes/.eslintrc.cjs
  packages/themes/default/.eslintrc.cjs
  packages/themes/ecl/.eslintrc.cjs
  packages/tools/kolibri-cli/.eslintrc.cjs
  packages/tools/visual-tests/.eslintrc.cjs
Labels: agent:codex

#7921 Fix aria-hidden usage in select options
  packages/components/src/components/select/shadow.tsx
  packages/components/src/components/select/test/__snapshots__/snapshot.spec.tsx.snap
Labels: agent:codex

#7932 CI: Upload Axe results and skip Axe tests when updating snaphots
  .github/actions/upload-reports/action.yml
  packages/tools/visual-tests/tests/axe-snapshots.spec.js
Labels: v2

#7939 Fix lang attributes in index pages
  packages/designer/public/index.html
  packages/samples/angular/src/index.html
  packages/samples/react/index.html
Labels: agent:codex

#7956 Visual tests: Fix sample app files list and add debug info
  packages/samples/react/.knip.json
  packages/samples/react/package.json
  packages/samples/react/tsconfig.json
  packages/samples/react/unocss.config.ts
  packages/samples/react/vite.config.ts
  packages/tools/visual-tests/src/index.js
  pnpm-lock.yaml
Labels: agent:copilot

#7957 feat(schema): add loading prop
  packages/components/src/components/image/shadow.tsx
  packages/components/src/schema/components/image.ts
  packages/components/src/schema/props/alt.ts
  packages/components/src/schema/props/image-sizes.ts
  packages/components/src/schema/props/image-srcset.ts
  packages/components/src/schema/props/index.ts
  packages/components/src/schema/props/loading.ts
Labels: agent:codex

#7958 docs: translate theme readmes to english
  packages/themes/default/README.md
  packages/themes/ecl/README.md
Labels: agent:codex, codex

#7960 fix(components): move vibrate comment to helper (#7191)
  packages/components/src/components/alert/component.tsx
  packages/components/src/functional-components/Alert/Alert.tsx
Labels: agent:codex

#7959 docs: update readmes for clarity (#7999)
  README.md
  license-reports/README.md
  packages/adapters/angular/v17/README.md
  packages/adapters/angular/v18/README.md
  packages/adapters/angular/v19/README.md
  packages/adapters/angular/v20/README.md
  packages/adapters/hydrate/README.md
  packages/adapters/preact/README.md
  packages/adapters/react-standalone/README.md
  packages/adapters/react/README.md
  packages/adapters/solid/README.md
  packages/adapters/vaadin/README.md
  packages/adapters/vue/README.md
  packages/components/README.md
  packages/components/src/components/README.md
  packages/samples/angular/README.md
  packages/samples/react/README.md
  packages/themes/README.md
  packages/themes/ecl/README.md
  packages/tools/kolibri-cli/README.md
  packages/tools/visual-tests/README.md
  scripts/README.md
Labels: agent:codex

#7951 Update lint/test instructions
  AGENTS.md
Labels: agent:codex
